### ISSUE TITLE
operators built with COMM_SELF dont handle subdimensions when used on COMM_WORLD

### ISSUE THREAD

**Issue by mikeando** [opesci/devito#1001]
At the moment I'm trying to build my operators on a grid using MPI.COMM_SELF, and then use them on a distributed grid using MPI.COMM_WORLD. In particular when switching to WORLD the boundary conditions get applied along the internal boundaries.

I've got an example  that reproduces this, showing that when the two communicators match then we get expected results, but when they dont match the boundary conditions are incorrect.

In my example I use $u_{n+1} = u_n + 1$ with the boundary condition $u = -1$. (This is _not_ the real equations we're interested in - just the simplest reproducer I was able to construct.)

First I construct some simple dimensions, for the interior calculations and the boundaries.

~~~

spacedims = ["x", "y"]
spacings = [Constant(name="h_%s" % d, dtype=np.float32) for d in spacedims]
dimensions = tuple(SpaceDimension(d, spacing=s) for d, s in zip(spacedims, spacings))
x = dimensions[0]
y = dimensions[1]
x_left = SubDimension.left(name="x_left", parent=x, thickness=bc_thickness)
x_right = SubDimension.right(name="x_right", parent=x, thickness=bc_thickness)
y_left = SubDimension.left(name="y_left", parent=y, thickness=bc_thickness)
y_right = SubDimension.right(name="y_right", parent=y, thickness=bc_thickness)
internal_dims = tuple(
    SubDimension.middle(
        name=d.name + "i",
        parent=d,
        thickness_left=bc_thickness,
        thickness_right=bc_thickness,
    ) for d in dimensions
    )
~~~

Next a simple function to create the operator using these:

~~~
def build_operator(name, comm):
    nx=10
    ny=10
    grid_shape = ( nx + 2 * bc_thickness, ny + 2 * bc_thickness,)
    grid = Grid( shape=grid_shape, dimensions=dimensions, comm=comm)
    u = TimeFunction(name='u',grid=grid, space_order=0, time_order=1)

    # Limit our update to the interior of the domain
    interior_eq = Eq(u.forward, u + 1)
    internal_dim_subs = {d: di for (d, di) in zip(dimensions, internal_dims)}
    interior_eq = interior_eq.xreplace(internal_dim_subs)

    # Limit out boundary conditions to the boundary
    bc = Eq(u,-1)
    x_left_bc = bc.xreplace({x:x_left})
    x_right_bc = bc.xreplace({x:x_right})
    y_left_bc = bc.xreplace({y:y_left})
    y_right_bc = bc.xreplace({y:y_right})

    actions = [interior_eq, x_left_bc, x_right_bc, y_left_bc, y_right_bc]
    return Operator(actions, name=name)
~~~

I then run these and dump the arguments to see what is going on

You can see the full application and its output when run with 2 ranks at this link: https://gist.github.com/mikeando/955703897b35fa3b523752041d61fee4

The key issue can be seen by comparing the WORLD+WORLD case loop bounds with the WORLD+SELF loop bounds

**op and grid both from WORLD (Correct)**
~~~
              Rank 0      Rank 1
bc x left  :  0 --  3  :  0 -- -1
interior xi:  4 -- 11  :  0 --  6
bc x right : 12 -- 11  :  7 -- 10
~~~

**op built with SELF, grid on WORLD (Wrong)**
~~~
              Rank 0      Rank 1
bc x left  :  0 --  3  :  0 --  3
interior xi:  4 --  7  :  4 --  6
bc x right :  8 -- 11  ;  7 -- 10
~~~

**Comment by FabioLuporini** [comment]
closing as fixed by #1009
