### ISSUE TITLE
Create Rayleigh wave

### ISSUE THREAD

**Issue by khwhw** [opesci/devito#1021]
Can i generate synthetic 2D Rayleigh waves data with K-Wave?

**Comment by mloubout** [comment]
Thanks for your interest. Could you detail a bit more what you are trying to d o and what issue you are facing?

**Comment by khwhw** [comment]
The medium consists of at least 2 layers, there is a cavity in the second and third layers where the Rayleigh waves hit the hole and return to the receivers on the surface to record the Rayleigh wavefield.Regarding to paper: "a numerical study of surface wave-based tunnel detection ...." https://doi.org/10.1190/geo2017-0467.1
I have pasted the image of the model I want to create.
Can you vreate this model for me please?
Best regards

**Comment by FabioLuporini** [comment]
> Can you create this model for me please?

We are not going to do that, but we are willing to discuss bugs, issues, and provide help either here or -- even better, so that the rest of the community can benefit -- on our Slack channel

**Comment by rhodrin** [comment]
As far I can tell, constructing such a model should be possible using custom stencils to represent the cavity. But this is something that should be discussed on slack and is not a Devito issue. Therefore closing this.
