### ISSUE TITLE
quality of generated code

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#108]
it's useful if we generate readable code. CSE helps, but it's not enough.

For example, at the moment we produce a long list of declarations:
``float temp1;``
``float temp2;``
``float temp3;``
``...``

Followed by a list of assignments
``temp1 = ...``
``temp2 = ...``
``temp3 = ...``

This essentially doubles the code size when hundreds of temporaries are used. We should rather have:
``float temp1 = ...;``
``float temp2 = ...;``
``float temp3 = ...;``

@vincepandolfo I'm assigning this to you but clearly this has lower priority than benchmarking

**Comment by vincepandolfo** [comment]
It was easier to do it this way in the python code to solve the issue of temporaries that need updating. Shouldn't be that hard to change, I'll give it a look when I get some time

**Comment by vincepandolfo** [comment]
Fixed in #117
