### ISSUE TITLE
Total loads count is not calculated appropriately by the Profiler

### ISSUE THREAD

**Issue by vincepandolfo** [opesci/devito#112]
Currently, the total number of loads does not take into account the indexes at which a load is performance.

For example, if `v[i1][i2][i3]` appears more than once in the code, every single instance of it will be counted as a different load.

This causes problems when calculating the optimal block size dimension based on the architecture.

**Comment by FabioLuporini** [comment]
so I assume this doesn't appear with CSE on ?

**Comment by vincepandolfo** [comment]
When CSE is on this problem is solved doesn't appear since multiple loads to the same index are factored out in temporaries

**Comment by FabioLuporini** [comment]
might actually not be true after all, because of the remainder loops

**Comment by mlange05** [comment]
If there is doubt about this it is probably under tested. Can we extend the current OI tests to cover blocking and/or CSE for some small examples to make sure?

**Comment by FabioLuporini** [comment]
Total load count now inferred directly in Python-land thanks to #136 . Closing.
