### ISSUE TITLE
Profiler: calculate total Flops count in Python

### ISSUE THREAD

**Issue by vincepandolfo** [opesci/devito#125]
Currently, we resort on parsing the C code and calculating the total flops count at runtime. Ideally, we would want to do this directly in Python since we know the loop limits and we can derive the number of operations per iteration from the Sympy expressions.

This is quite hard to do with the current state of the `Propagator` (it would also make the code much messier that what it already is) but it should become much easier when the `Propagator` will be rewritten to make use of `Iteration` and `StencilKernel` classes.

We should keep this issue in mind when building the new `Propagator`

**Comment by FabioLuporini** [comment]
Fixev via #136
