### ISSUE TITLE
Devito `Dimension` objects don't match `sympy.abc` symbols 

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#141]
The following snippet works and creates a `sympy.Derivative` object:

```
from devito.import TimeData, x
f = TimeData(name='f', shape=(3, 3), time_order=1, space_order=2)
print f.diff(x)
```

However, the statement below prints `0`, although both should be equivalent:

```
from devito.import TimeData
from sympy.abc import x
f = TimeData(name='f', shape=(3, 3), time_order=1, space_order=2)
print f.diff(x)
```

**Comment by mloubout** [comment]
#369 should have fixed it as dimenions are now "self-contained", not symbols anymore. @mlange05 closing?

**Comment by mlange05** [comment]
Yeah, not really an issue anymore, as `Dimensions` have become way more that just symbols. So closing.
