### ISSUE TITLE
Enforce thread pinning through `Compiler` class

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#143]
In order to ensure reproducible performance evaluation on NUMA systems we should enforce thread pinning in our `Compiler` classes for the most common tool chains (GNU and KMP). The challenge I see though is that simply "unrolling" the processor IDs as `[0, .., N]` might not be portable, since processor ID numbering conventions can vary between CPU generations. More generic settings like `compact` or `scatter` (KMP) might need to be explored for and compared to the "hand-unrolled" settings we use at the moment.

**Comment by ggorman** [comment]
I'm concerned this is a fools errand. The OpenMP standard already defines OMP_PROC_BIND and OMP_PLACES - and this appears to be the only portable solution on offer. Every compiler writer and job scheduler appears to want to introduce their own "helpful" abstraction for doing the same job.

**Comment by mlange05** [comment]
But we have compiler-specific configurations built-in, so all we need to figure out what the portable way to do this is for Intel's KMP and maybe GCC.

**Comment by ggorman** [comment]
However, the OpenMP standard committee already came up with a portable solution for this - namely OMP_PROC_BIND and OMP_PLACES. You need to have a very good reason to reject the OpenMP standard and come up with something different.

**Comment by mlange05** [comment]
I take it that this is now orphaned and we're leaving it to the user to do the right thread-pinning for performance runs? If so, this can be closed, but I'd like an ack before I do so.

**Comment by navjotk** [comment]
I vote to keep this open even if low priority. 
We promise performance portability - something that we can't offer unless we do this. This also hits the reproducibility of our results - something that is required for publishing anything. 

AFAIK, what @ggorman suggests above still needs to be implemented, i.e. something needs to set those env vars.

**Comment by FabioLuporini** [comment]
There's now a README  (PERFORMANCE.md) that helps with understanding how to do this sort of (user- and machine-specific) settings.

Shall we close this?

**Comment by FabioLuporini** [comment]
@ggorman thoughts?

**Comment by FabioLuporini** [comment]
I think what people should instead of using env variables, is simply to use ``numactl``. This is what @chuckyount and I do for performance runs. In light of that, I think we should close this.

**Comment by navjotk** [comment]
I think the core point of this issue is that devito should automatically configure the environment to maximise performance - for performance portability and reproducibility. Whether it is through environment variables or through `numactl`, SOMETHING in devito should be doing this before the heavy runs start.

**Comment by FabioLuporini** [comment]
It is bad practice that a tool like devito would by default make decisions about number of threads and their placement. Especially on clusters, this might have unexpected consequences. 

I'm introducing this instead: https://github.com/opesci/devito/pull/783/files#diff-dddb71f39e89711fba9e88dd21f9fe1dR1

thoughts?
