### ISSUE TITLE
Intermittent TTI failures on Travis OSX

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#146]
The travis OSX builders frequently, but not regularly, segfault on the the standalone TTI example test. Presumably this might be due to the shaky nature of the travis OSX builders, so OSX testing is temporarily disabled. If anyone is interested in debugging and fixing this, simply remove the `allow_failures` line from the build matrix in `.travis.yml`.

**Comment by mloubout** [comment]
It seems to be fine now right?

**Comment by mlange05** [comment]
Well, it's disabled and not really fixed. However, travis doesn't support Python projects on OSX natively at the moment, so I think we can close the issue for now.
