### ISSUE TITLE
Browser-based configuration GUI

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#148]
The first step towards a Devito web interface is a basic browser-based UI that provides similar capabilities to the current `examples/benchmark.py` script (select equation type, spatial order, etc.). The web interface should be based on the [flask](http://flask.pocoo.org/) package and a UI template page, possibly based on [Jekyll](https://jekyllrb.com/) or similar. The aim is to be able to invoke a local benchmarking run through the browser GUI.

**Comment by mlange05** [comment]
An example of a configuration GUI similar to the one envisioned can be found in the `web_config` branch of the [firedrake](https://github.com/firedrakeproject/firedrake) repo (currently under review as PR #874).

**Comment by FabioLuporini** [comment]
no more interest in this, so closing.
