### ISSUE TITLE
Reduced test base for installation testing

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#185]
We need to mark some tests as essential to produce a reduced test base to be run at installation time. 

These tests will be used to test that an installation has been completed successfully. Running the complete test base for this purpose is an overkill and excessively time consuming.

**Comment by FabioLuporini** [comment]
I think this is a non-issue, or at least, AFAIK, we don't run any tests when installing Devito

**Comment by tjb900** [comment]
I think this might still be a good idea, if only to detect some of the issues with dependent projects (take @ggorman 's dramas with numpy.dot, for example, or the sympy issue we are waiting for a fix for).

**Comment by ggorman** [comment]
I propose we close this as test coverage is now enhanced in PR #585; if there are important platforms that we have missed then its easy to use the script to generate a new set of VM's. To go further than that I think we should instead be looking at some of the code verification techniques that Jan and Paul have spoken about - in which case we also have to have a specification language etc.
We should also remember that the user is always free to run the tests by hand...

**Comment by FabioLuporini** [comment]
Perhaps we should at least run ``test_dependency_bugs.py``

**Comment by ggorman** [comment]
No longer relevant.
