### ISSUE TITLE
Generalise point interpolation

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#189]
The current way sources and receivers are makes implicit assumptions about the expression to interpolate and only allows restrictive overrides of the time indices. This is partially tweaked in PR #187, but it requires a more generalised re-think of how we want to treat point interpolation in the Devito3.0 API. A core observation is that the `PointData` base should probably provide the interpolation weights, while allowing the user to define arbitrary expressions to interpolate.

For this two cases need to be considered:
* Grid-to-point interpolation (receiver): Single expression collecting contributions from multiple grid points
* Point-to-grid interpolation (sources): Multiple expressions updating the neighbouring grid points

As a first idea, how about something like this (assuming `PointData src, rec` and `TimeData u`):
```
# Grid-to-point
src(time, p) = sum([w * u(t + 1, idx) * <something> for idx, w in src.index_weights])

# Point-to-grid
[u(t, idx) = w * u(t, idx) * <something else> for idx, w in rec.index_weights]
```
The above is pretty close to what we do right now under the hood, where `w` is the contribution weight, and `idx` is an expression for the dynamic grid indexing in space.

**Comment by mloubout** [comment]
@mlange05 I think this is fixed with the new `pointdata`. Closing?

**Comment by mlange05** [comment]
Yes, closing.
