### ISSUE TITLE
Logging mechanism

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#19]
We need a logging system to make it easy to find errors.
The same (or a different?) mechanism could be used for profiling and benchmarking.

**Comment by ggorman** [comment]
Possibly adopt petsc event logging?

**Comment by mlange05** [comment]
We don't yet depend on petsc, so adding such a heavy dependency just for the profiling seems overkill, at least for now.

The logging part should be easy, we can use standard Python utilities or just write a small utility function ourselves. For profiling, I think we can roll our own for now; simply collect the relevant timings and OI numbers on all ranks, gather them into rank 0 using `mpi4py` and then drop them to file using the `json` package which keeps things reasonably tidy. Alternatively we could explore `pytest-benchmark` and see if this fits our needs. Any other suggestions are of course appreciated.

**Comment by navjotk** [comment]
PR #61 address this
