### ISSUE TITLE
Expose kernel argument order to external callers 

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#191]
For user libraries aiming to manually load and call kernels compiled from Devito3.0 we should expose the list of C arguments and allow external overrides. This is necessary since the 3.0 API will generically infer the argument order from the stencil expressions themselves, which is hard to predict from the outside. Since we match all args by name internally we are not bound to that order in `StencilKernel.apply()` and can therefore easily expose something like this:
```
operator = StencilKernel([<expr1>, <expr2>])
operator.set_arg_order(['u', 'm', 'src', 'x_size', 'y_size', 'x_block_size', ...])
operator.compile()

<Let someone else load and run the kernel>
```

**Comment by mloubout** [comment]
Fixed with `external` operators, closing.
