### ISSUE TITLE
Clean up CFL condition implementation

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#203]
We currently have hard-coded magic numbers in the CFL condition that only work for certain discretizations and might lead to problems when we start playing with different discretizations. 

I think this could be calculated automatically since we have the FD coefficients at the symbolic level.

**Comment by mloubout** [comment]
Can we close this?

**Comment by FabioLuporini** [comment]
is this still an issue?

**Comment by mloubout** [comment]
I don't think so. Closing.
