### ISSUE TITLE
PML

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#21]
@navjotk 
damp proflile needs to have a 3D condition as discussed yesterday

**Comment by navjotk** [comment]
Does 36512d1308e1ee230236562507bbace4486fced9 address this?

**Comment by mloubout** [comment]
the index -i has to be changed to -(i+1), last index is -1 not -0

**Comment by navjotk** [comment]
Fixed in 9ab63b54f32b271f660e82349db61c1bd13c7604

**Comment by navjotk** [comment]
Fixed in 97b0d1f3c9ea67880d897aa0137d23b728c30235

**Comment by mloubout** [comment]
pos = np.abs((nbpml-i)/nbpml)
has to be replaced by
pos = np.abs((nbpml-i)/float(nbpml))

it always returns 0 except for i=0 otherwise

**Comment by navjotk** [comment]
Fixed in 63dc2b509c030fca2d3e5f4efba91906965d23dd

**Comment by navjotk** [comment]
@mloubout could you help me figure out why the adjointA test fails in f2c70be808f5e88fb1b5aada226859cd9b679e1a ?

**Comment by navjotk** [comment]
Should we close this now, after 5ee60fbe3ad7db5826f3b02cfc4d415a7e482964 ?
