### ISSUE TITLE
Interface to Revolve Checkpointer

### ISSUE THREAD

**Issue by jhueckelheim** [opesci/devito#216]
**Update: The interface has changed, see my comment below.**

The Revolve Checkpointing library needs an interface to work with Devito. All the points below are my current working assumption and up for discussion. If you don't know what this is about, read the following block of text, else goto Devito.

> # Recap: Checkpointing
>
> The adjoint computation of an unsteady nonlinear primal function requires the full primal trajectory in reverse temporal order. Storing this can exceed the available memory. In that case, Checkpointing can be used to store the state only at carefully selected points in time. From there, the forward computation can be restarted to recompute lost sections of the trajectory when they are needed during the adjoint computation. This is always a tradeoff between memory and runtime. The classic and provably optimal way to do this for a known number of time steps is [Revolve](http://dl.acm.org/citation.cfm?id=347837.347846). For a previously unknown number of time steps, there's an [optimal online version](http://dl.acm.org/citation.cfm?id=1654955). For a two-stage storage system (e.g. memory+HDD) there's also an optimal [multistage algorithm](https://hal.inria.fr/hal-01147155/document).
> 
> We are working on a python checkpointing library that wraps around an open source C++ checkpointing library. That library only provides a schedule, i.e. it decides when to store checkpoints. On top of that, we are creating a library (the "Checkpointer", "Revolver", naming suggestions welcome) that performs the actual data and computation management. This library needs to split the forward computation in a number of chunks, store a copy of state variables at the end of each chunk, interleave multiple calls to forward and adjoint operators, and inject data back into the forward operator to resume the computation from a previously stored state. Using this in Devito requires some communication between the Checkpointer and Devito operators.

# Devito

 - users need to pass `forward_operator` and `reverse_operator` to the Checkpointer.
 - These objects need to have
    - an `input_arguments()` routine that returns a list of references to Symbol objects that are read
      by this operator (this may not change throughout the computation),
    - equally an `output_arguments()` list of Symbol objects that are modified,
    - an `apply(time_steps, **kwargs)` routine that performs the prescribed number of time steps. `apply` must accept whatever data is within the symbols as the intial state for that computation, and the forward operator may not have side-effects and only access the symbols given in `kwargs`. This can probably be relaxed for the reverse operator if needed.
 - The Symbol objects need
    - an `nbytes` property that reports the size of this object in memory, and
    - a `data` property with a `deep_copy` routine.
    

# Checkpointer

  - provides `__init__(fwd_op, rev_op, time_steps)`, and
  - the `apply(**kwargs)` routine, where `**kwargs` contains all symbols used by the operators, initialised to their initial conditions. On return, the data within the symbols in `forward_operator.output_arguments` is guaranteed to be in the final state after performing `time_steps` steps, and the data in `reverse_operator.output_arguments` is guaranteed to contain the adjoint state for the initial time.
  
# Open Questions

 -  By default, should the checkpointer use all available memory? If not, what else? Do we want handles to limit the number of snapshots, or absolute or relative memory consumption? A good interface is needed for multistage checkpointing (fast-ram<ram<ssd<disk), with limits for each stage and speed factors between them, with reasonable default behaviour.
 - There are complications for higher-order in time operators, where a single checkpoint contains multiple time steps, and resuming from such a checkpoint is not the same as starting from some initial condition. The `operator.apply` routine needs to be able to distinguish between "initial" data (e.g. all zeroes) and computed data. Ideally this information would be stored within the `Symbol.data` and be preserved through the `deep_copy` routine.
 - If the number of time steps is not known a priori, we can use online checkpointing algorithms. In that case, the forward operator must inform the Checkpointer when the computation is complete. Maybe a return code?

# "Future work": issues to keep in mind

 - Michael and I discussed operators that are optimised (e.g. with time-tiling) for a certain number of contiguous time steps. I am now assuming that this would be implemented within the operators and not be visible to the outside, i.e. the operator would internally select the best implementation for the requested number of time steps. Everything else would force the Checkpointer to be concerned with internal optimisations within the operators, but I am open for convincing arguments.
 - There's potential for the operators to screw things up in a way that will silently cause wrong results only when checkpointing is used (e.g. side-effects, returning incomplete lists of input and output args). We need tests for the Checkpointer, but also for the operators. Freedom of side-effects may be hard to test automatically.
 - The state variables that are checkpointed are for now the intersection of `fwd_operator.input_arguments` and `fwd_operator.output_arguments`. This is a crude assumption that works for now. I might switch this to the intersection of `forward_operator.input_arguments`, `forward_operator.output_arguments`, and `reverse_operator.input_arguments`.

**Comment by jhueckelheim** [comment]
An example for the difficulties with higher order:
A BDF2 stencil requires two previous time steps, i.e. `u[t]=f(u[t-1],u[t-2])`. At `t=1` there are no two previous time steps. The solvers that I have encountered use a lower-order method to ramp up. Let me know if Devito does something else.

To preserve the temporal order, we have to ensure that not just the current time step is stored, but also enough previous time steps. I assume that the `Symbol.data` object contains several time steps and that its `deep_copy()` routine will copy them all.

In addition, it is then necessary that the `forward_operator.apply()` routine will actually utilise the available data with a higher-order method whenever possible.

It is not enough to pass a switch between initialisation and continuation to `apply`. Let's assume that we have an `n`-th order method that ramps up during the first `n` iterations. Let's further assume that a checkpoint is stored at the `n-1`-th iteration. Now the computation may have to resume somewhere within its ramping up phase.

I see two ways out of this:

1. The `Symbol.data` can inform the operator about the number of precomputed time steps that it contains. This way, the concern is only with the operator and the data, while the checkpointer does not need to know anything about temporal order.
2. The `Operator.apply()` routine takes the number of available steps as an optional argument, and returns to the caller the number of time steps that need to be checkpointed to resume from the current state.

There is a future improvement that is possible with option 2: Towards the end, the distance between checkpoints becomes small. If, for example, we store a checkpoint at every step, but each checkpoint contains 2 time steps, we store redundant data. If the checkpointer knows about the temporal order and the `Symbol.data.deep_copy()` routine allows the selective copying of time steps, the checkpointer can keep track of this and store only what is necessary.

**Comment by mlange05** [comment]
I think for higher-order in time problems we will always require some level of tracking the current state of the modulo buffers within `TimeData` objects, not only for the checkpointing but a nicer user interface. Issue #69 captures that problem already. 

That being said, I believe capturing the redundancies between small checkpointing steps (option 2) is also necessary to optimise overheads and space usage, but this might be an optimisation further down the line.

**Comment by jhueckelheim** [comment]
After last afternoon's discussion, here's a new take on the interface between pyrevolve and devito.

pyrevolve will provide an abstract base class "Checkpoint" that must be extended by a user of pyrevolve, and must provide

- a `size` property, containing the size of a checkpoint in Bytes,
- a `save(ptr)` method that deep-copies all live data that needs to be checkpointed into the provided location inside the Checkpoint storage, and
- a `load(ptr)`method that deep-copies all data from the given location back into the live data.

To implement this Checkpoint class, a user will require the symbol deep_copy routine. In addition, pyrevolve requires that the operators accept `t_start` and `t_end` parameters, and can resume their operation on the live data without confusing the state of the buffer. This is described in the related issue https://github.com/opesci/devito/issues/247.

The actual computation will operate like this:

1. The user initialises the operators with whatever symbols are required, and implements a concrete implementation of the Checkpoint object with the above properties.
2. The user calls pyrevolve, with the arguments: `fwd_operator`, `rev_operator`, `n_time_steps`, `n_checkpoints`. (Other options will follow in the future, e.g. online checkpointing, multistage, etc.).
3. On initialisation, pyrevolve will query `checkpoint.size` for the size of one checkpoint, and allocate `n_checkpoints*checkpoint.size` bytes of memory for checkpoint storage.
4. Repeatedly, pyrevolve will call either of the following actions in the user-defined Checkpoint and operators: `fwd_operator.apply(tstart, tend)`, `rev_operator.apply(tstart, tend)`, `checkpoint.save(ptr)`, `checkpoint.load(ptr)`, where `ptr` will point to the start of the appropriate checkpoint in the storage.
5. pyrevolve may in the future use multi-stage checkpointing to swap checkpoints to disk (asynchronously?), but `ptr` as passed to `checkpoint.save` or `checkpoint.load` is guaranteed to point to a checkpoint that is available in memory.

**Comment by navjotk** [comment]
Can this be closed @jhueckelheim ?

**Comment by FabioLuporini** [comment]
updates @jhueckelheim ?

**Comment by FabioLuporini** [comment]
updates @jhueckelheim @navjotk
