### ISSUE TITLE
Finalising basic 3.0 operator API

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#226]
This is an umbrella issue that highlights the remaining step to be taken to replace the legacy operators with the new 3.0 generic ones (formerly `StencilKernel`). It is not a complete guide to the 3.0 release, although it should get us very close. I will update this as we go along

Bare minimum:
* Fix and merge PR #223 - @navjotk 
* Use #223 to remove "model-rng" hack from #210 - @mloubout 
* Fix any remaining legacy+DSE/DLE problems (issue #218)  - @mloubout @FabioLuporini 
* Merge #210 following above fixes and with all seismic tests using `legacy=False`
* Address issue #189 by landing existing branch `pointdata-cleanup` - @mlange05
* Remove `Operator` and rename `StencilKernel` -> `Operator`
  * Fix and consolidate legacy-specific tests
* Re-write and clean up utility classes and wrappers for seismic examples, in particular with respect to operator caching as described in issue #227 - @navjotk @mloubout @mlange05

For added bonus points:
* **Tutorials and documentation**
  * API overview with worked example (see final point above)
  * Developers guide with internal code structure diagram and a "Rough guide to real compiler magic" - @mlange05 @navjotk @FabioLuporini  
* Fix the auto-indexing of the time buffers described in issue #69
* Various other fixes described in issues #190, #191, #192, #193

**Comment by FabioLuporini** [comment]
Great. On it.

**Comment by navjotk** [comment]
Can you be more specific on what in #223 needs fixing?

**Comment by mlange05** [comment]
@navjotk Pinged on the relevant PR.

**Comment by mlange05** [comment]
Ok, small updates to the bonus list, and re-pointed the seismic example clean-up point.

**Comment by mloubout** [comment]
Looks good,
- Re-write and clean up utility classes and wrappers for seismic examples, in particular with respect to operator caching as described in issue #227 - @navjotk @mloubout @mlange05

I don't think this one is major for the Paper.

**Comment by mloubout** [comment]
- Remove Operator and rename StencilKernel -> Operator
Some tests need to be removed/rewritten. For example, `test_cache_blocking` is outdated and segfault. I can start to remove operator, but I will have to remove related test That I don't know how to rewrite with `StencilKernel`

**Comment by mloubout** [comment]
- Re-write and clean up utility classes and wrappers for seismic examples, in particular with respect to operator caching as described in issue #227 - @navjotk @mloubout @mlange05

I have an idea of how to do it, but it needs #210 to land os that I can removed a bunch of old stuff from Operator/Propagator.

**Comment by FabioLuporini** [comment]
I think we can close this @mlange05

**Comment by mlange05** [comment]
Yes, 3.0 has landed, so closing...
