### ISSUE TITLE
StencilKernel dimensions check

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#228]
This about a bug I just found out trying to figure out why `adjointJ` wasn't working anymore.

`f_args = [f for f in arguments.values() if isinstance(f, SymbolicData)]` Line 144 in `StencilKernel` produces something like :

`[damp(x, y), m(x, y), rec(time, p_rec), rec_coords(p_rec, d), src(time, p_src), src_coords(p_src, d), u(t + s, x, y)]`

and form this, the dimensions are inferred as : 

`{t: 3, d: 2, y: 130, time: 215, x: 120}`

However, if the order is changed to:
`[u(t + s, x, y), damp(x, y), m(x, y), rec(time, p_rec), rec_coords(p_rec, d), src(time, p_src), src_coords(p_src, d)]`

the dimesion size become:

`{d: 2, y: 90, time: 3, x: 80, t: 3, x_block: 8}`

and `time` has the wrong size.

This happens in Born because one of the field is called `U` and that end up first in the list because it's an upper case. renaming it `ub` fixed it but this is a very dangerous bug to leave in there.

**Comment by mlange05** [comment]
Fixed via #234, I believe. @mloubout can you confirm and close please?

**Comment by mloubout** [comment]
Looks good, closing.
