### ISSUE TITLE
Strange behaviour of TimeData constructor

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#236]
The behaviour of `TimeData` is essentially broken unless the `shape` property is directly provided in the constructor. If a time dimension is passed explicitly, the shape is incorrectly inferred. If it is not passed, the functional indices are incorrectly inferred which breaks `schedule_expressions` in `StencilKernel`. 

```
>>> from devito import TimeData, t, time, x, y, z
>>> a = TimeData(name="a", dimensions=(x, y, z), time_dim=100)
>>> a.indexed.function
a(x, y, z)
>>> a.shape
(2, None, None, None)
>>> b = TimeData(name="b", dimensions=(time, x, y, z), time_dim=100)
>>> b.indexed.function
b(time, x, y, z)
>>> b.shape
(2, None, None, None, None)
```

**Comment by mloubout** [comment]
> `b = TimeData(name="b", dimensions=(time, x, y, z), time_dim=100)`

This is an odd way to declare it. You create a time data object with two time dimensions. If you add `time` in dimension you don't have to respecify it in `time_dim`.

**Comment by navjotk** [comment]
```
>>> c=TimeData(name="c", dimensions=(time, x, y, z))
>>> c.indexed.function
c(time, x, y, z)
>>> c.shape
(2, None, None, None, None)
```

**Comment by mloubout** [comment]
As I said, `TimeData` is `dimension + time_dim` if you put `time` in dimensions you add a second time dimension. The behavior s not broke as it does what it is supposed to, it main be a design flow if that's not the best way to do it.

**Comment by navjotk** [comment]
My first example was without putting in the time dimension explicitly. In that case, `a.indexed.function` (which is the symbolic representation) does not contain a time dimension. Since the `Operator` uses this symbolic representation to figure out the dimensionality of the object, I can't do this to the `a` object in my example code: `a=1` or `a[time, x, y, z]=1`. `Operator` croaks about not finding a `time` dimension since it uses `a.indexed.function` to find the dimensions. 

Essentially there is no way to instantiate a `TimeData` object purely from `Dimension`s (and not passing a shape) and use the object in an `Operator`.

**Comment by FabioLuporini** [comment]
@mlange05 This can also probably be closed

**Comment by navjotk** [comment]
At least write something about this in the docstring before closing the issue.

**Comment by FabioLuporini** [comment]
I thought this was "fixed" because a merged PR (#257) was referencing this issue.

**Comment by navjotk** [comment]
The "fix" needs to be explained in the docstring as two examples: one would be initialisation with shape, the other initialisation with dimensions. I don't see that in #257 .

**Comment by FabioLuporini** [comment]
I agree; I thought for a moment that you meant that the issue wasn't actually fixed. Please someone step up and do as Navjot says

**Comment by mlange05** [comment]
Ok, I thought I added some clarification to the `TimeData` docstring in #257:
`dimensions – The symbolic dimensions of the function in addition to time.`
and
```
The temporal dimension will be inserted automatically as the leading dimension,
according to the :param time_dim:, :param time_order: and whether we want to
write intermediate timesteps in the buffer. The same is true for explicitly provided
dimensions, which will be added to the automatically derived time dimensions symbol.
```
Is that not clear enough? @navjotk

**Comment by mlange05** [comment]
Ok, it looks like some docstrings in `interfaces.py `are kind of borked anyway. I'll have a go at sanitising some of this...

**Comment by FabioLuporini** [comment]
Fixes, so closing.
