### ISSUE TITLE
Time bounds

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#238]
Ok, so we are back at it. The time loop limits are not estimated correctly if the first stencil is not a `TimeData` object.

As for `Adjoint` the loop limits are :
`for (int time = time_size - 2; time > 1; time -= 1)`

But for the gradient, if I replace 
`[eqn] + [gradient_update] + rec_add`
by
`[gradient_update] + [eqn]  + rec_add`
the loop becomes 
`for (int time = time_size - 1; time >= 0; time -= 1)`
and try to access `u[time_size]` and `u[-1]`

**Comment by mloubout** [comment]
And also on another note (can file a different Issue if necessary):
`src_add + [eqn] + rec_read `
`rec_read + [eqn] + src_add `
also gets the bounds wrong (with `save=True`) and
`rec_read + [eqn] + src_add ` with `save=False`
only fail to compile as the `rec_read` part has it's own time loop before the pde part.

**Comment by FabioLuporini** [comment]
Please take a look at #245

**Comment by mloubout** [comment]
Not fixed, loop limits still wrong with `src` or `rec` first.
With `[gradient_update] ` first, the gradient stencil is still separated from the rest (full time loop for gradient then full time loop for the rest, so stencil dependencies are not caught properly I guess).

**Comment by FabioLuporini** [comment]
I guess what you wrote before the edit was wrong?

**Comment by mloubout** [comment]
Yes, tried the wrong branch :(

**Comment by mloubout** [comment]
Fixed in #245, closing.
