### ISSUE TITLE
Python-debug mode via sympy.lambdify

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#244]
The new 3.0 `Operator` class unfortunately did not feature a Python-debug mode any more. Since this, however, can be quite a useful feature during development, we should re-instate it soon. For this we can use  the new internal `Operator` hierarchy and combine the automatic argument derivation routines with `sympy.lambdify` to provide a fully automated front-end to the SymPy JIT capabilities.

**Comment by ggorman** [comment]
Closing due to lack of demand.
