### ISSUE TITLE
Add Devito features required for checkpointing

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#247]
To introduce checkpointing, Devito requires some additional features.

Following from the last discussion, this is to document the changes that will be made in Devito to enable the use of checkpointing:

1. **Start and stop Operators at a given time-step**: Add optional parameters to `Operator.apply()` called `tstart` and `tend` to (re)start the Operator from a given time-step and run for a given number of time steps. 

2. **Store last accessed time step in data objects**: This is largely related to issue #69 where, when a `TimeData` object has a buffered time dimension, it is not clear which buffer holds the field computed at the last time-step. Currently we are working around this by externally tracking the number of time-steps that were run on the object. This should be internalised so that external code can reliably know how to access the last computed field. There was a proposal to do the same for `PointData` objects as well but I don't remember the argument for that - could potentially be discussed (again). 

3. **Deep copy routines inside symbolic data objects**: All symbolic data objects to have a `save` routine to save their state (data as well as the internal time counter added by the above, to start with) in a memory location provided by the caller. There would also be an accompanying `restore` method to restore state from a provided memory location. A corollary to this would be that a symbol should be aware of and be capable of reporting the amount of memory required to save its state. This knowledge would eventually find its way into the checkpointer which would be responsible for allocating memory to store the checkpoints.

**Comment by navjotk** [comment]
I discussed point 1 with @FabioLuporini today and we agreed that the cleanest way to implement this would be to extend the parameter that is currently used to pass the number of timesteps, `t`. The current code assumes that the loop will run from `t=0` to `t=<provided value>`. We could extend that code to also accept 2-tuples and default to `(0, <provided value>)` in case a scalar is passed. (All this extends naturally to all dimensions)

This leads to my question: how does this relate to the `direction` parameter? We could either:
- Assume that the first element in the tuple represents the loop starting value and the second the end value. This makes the direction parameter redundant since reversing the order of this tuple would achieve reversing any loop. 
- Assume that the first element of the tuple is always less than the second and the direction of traversal in this space is provided by the direction parameter. 


Thoughts?

**Comment by FabioLuporini** [comment]
I prefer the former of the two, I think. And yes, I agree the ``direction`` parameter would have to be dropped in that case, which would make me even happier

**Comment by navjotk** [comment]
Due to implementation complexities, I believe it is much better to implement `2.` above although in theory I do prefer `1.`. I am currently working on that.

**Comment by mlange05** [comment]
Yes, while 1. sounds nice, the core thing to find is a general loop condition statement that does not include performance-crippling conditionals. Does anyone know how this can be done elegantly? @FabioLuporini

**Comment by navjotk** [comment]
I think the core issue here is: the user will not want to reuse the same operator for a forward AND backward run (although this works for the acoustic wave equation, it is not generally helpful). By removing the `reverse` parameter and allowing the user to choose direction at apply time, we are jumping through a lot of hoops to provide a piece of functionality that is not required.

When a user creates an `Operator` it is usually clear to them at creation time whether they will be using this `Operator` in forward or reverse mode. Our generated code is made complex because we ignore that piece of information. By not accepting this bit of information at construction time, we are generating code that is unnecessarily general - missing out on the domain specialisation. 

Hence 2 is better in the sense that it allows devito to capture information as it becomes available (about the direction of propagation).

**Comment by mlange05** [comment]
> I think the core issue here is: the user will not want to reuse the same operator for a forward AND backward run (although this works for the acoustic wave equation, it is not generally helpful). By removing the reverse parameter and allowing the user to choose direction at apply time, we are jumping through a lot of hoops to provide a piece of functionality that is not required.

I entirely agree. In fact direction really only matters for time, whereas the ability to dynamically define ranges at runtime might be incredibly usefull for things like sub-domain traversals (eg. sub-regions or BCs over parts of a boundary). So I think there is little harm in not generalising direction, but sub-ranges should be available for general dimensions.

**Comment by FabioLuporini** [comment]
Agreed.

**Comment by navjotk** [comment]
This, I believe, should have been closed a long time ago.

**Comment by FabioLuporini** [comment]
I didn't close it because points 2. and 3. were still missing, but if we don't need them, yeah, pls go ahead and close it
