### ISSUE TITLE
The Operator API could take inspiration from loopy

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#25]
The project [loopy](https://documen.tician.de/loopy/) does something quite similar to what Operators in devito are doing. Probably their API is a good model for us to target.
Edit: To clarify - loopy is a suggestion for what the API should look like to the user of devito - there is no intention to interface with loopy.

**Comment by ggorman** [comment]
Loopy itself targets OpenCL and CUDA. However, KNL doesn't support OpenCL AFAIK. How about http://www.cloog.org?

**Comment by navjotk** [comment]
Are you suggesting we interface with cloog?

**Comment by ggorman** [comment]
I believe this is what Michael is advocating for. We probably need to do a
more complete review of our options at this point.

**Comment by navjotk** [comment]
In that case, its not what I opened this issue for. I was saying the Operator API could *look like* the loopy API - not interface with it. Maybe I should clarify that in the opening post.

**Comment by mlange05** [comment]
I think an example of what you mean by a "loopy-inspired" operator API would really help this discussion.

Also, I am not advocating a  Cloog front-end (yet), since this could easily become very tedious. I was hoping that Intel compiler directives for loop blocking could make this easy, but I am unsure at the moment. A more detailed review should indeed be done first.

**Comment by mlange05** [comment]
After implementing the first wave of some symbolic automations (PRs #35 and #42), I don't think the LooPy API is what we're aiming for for the Operator. Instead, I think our Operator API should be based on `sympy.Equation` objects, and should encapsulate the symbolic steps required to get to our low-level Propagator API that auto-generates FD kernels. Therefore I think this can be closed, @navjotk?

**Comment by navjotk** [comment]
I agree. Closing
