### ISSUE TITLE
from devito import *

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#252]
Shouldn't we automatically import all or key ``sympy`` types when doing ``from devito import *`` , such as ``Eq, ...``? Which is sort of the Devito language

**Comment by mloubout** [comment]
Where do we have that?

**Comment by navjotk** [comment]
I am not sure I understand why we would want that since [pep8](https://www.python.org/dev/peps/pep-0008/#imports) recommends avoiding wildcard imports.

**Comment by FabioLuporini** [comment]
Because we are a super special case -- it's the magic statement you need to have the "Devito language(s)" at your full disposal

Same strategy adopted in FEniCS and Firedrake

**Comment by navjotk** [comment]
I personally dislike namespace clutter so in my opinion this is a non-issue. But that's just me.

**Comment by FabioLuporini** [comment]
> this is a non-issue

That's why I had marked it as ``question`` :) I however prefer the ``from devito import *`` (only because this is a special case, in user-land)

**Comment by FabioLuporini** [comment]
Fine, closing
