### ISSUE TITLE
Dimensions argument not passed between run() and setup() in acoustic example

### ISSUE THREAD

**Issue by dymcc** [opesci/devito#274]
I make use of the acoustic example setup code to do experiments for my master's project with Fabio.
The latest version (#256) of `acoustic_example.py` has a spelling mistake in the newly introduced `run()` / `setup()` logic which makes the `setup()` function always use the default value for the `dimensions` argument.

Python is very sneaky about this... 

https://github.com/opesci/devito/blob/cc772c7f282fe6989af735c3c73a42f3187e7de9/examples/seismic/acoustic/acoustic_example.py#L81

**Comment by mloubout** [comment]
Thank you for the info, good catch. Will fix it asap.

**Comment by dymcc** [comment]
Didn't see your comment until after submitting the pull request :shipit:

**Comment by FabioLuporini** [comment]
Closing this, as the relevant PR has been merged
