### ISSUE TITLE
Container for managing wave-field time history

### ISSUE THREAD

**Issue by ggorman** [opesci/devito#29]
Need to add a container for storing the time history of the forward model.

Strict requirements:
1. API should be abstracted for opesci/devito so that the container backend can be replaced in the future if necessary.
2. Support for very large datasets - out of core support.
3. Configurable to use available RAM - spilling to disk when necessary.
4. Need to be able to specify storage device.

Desirable features:
1. Data structure should behave as a stack - i.e. last in first out (LIFI) data structure.
2. Support for non-blocking push and pop.
3. Prefetching from disk while popping. 

Initial suggestion is to build support around stxxl::stack - http://stxxl.sourceforge.net/tags/master/tutorial_stack.html

**Comment by mlange05** [comment]
Did the recent `memmap` PR address this problem in full? Can this now be closed?

**Comment by ggorman** [comment]
I believe so. We can close this issue for now as it's use if explored in
the inversion repo.
