### ISSUE TITLE
sympy 1.1

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#291]
Sympy has been updated to 1.1 on July 6 and devito is not compatible with it.

I would detail why but I honestly have no idea why it is broken. There is two things 

1- `as_finite_diff` is deprecate,  trivial to update and not used in acoustic so not relevant
2- IndexedBased object are symbols  `is_Symbol=True` making it hard to differentiate between indexed and symbols and breaking our code generation workgflow.

I do not know if we want to "upgrade" devito or force sympy 1.0

**Comment by mloubout** [comment]
`sympy 1.0` : 

```
from sympy import IndexedBase

In[7]: x = IndexedBase('x')
In[8]: x.is_Symbol
Out[8]: 
False

```


`sympy 1.1` : 

```
>>> from sympy import IndexedBase
>>> x = IndexedBase('x')
>>> x.is_Symbol
True
```

**Comment by FabioLuporini** [comment]
This has been fixed. Closing.
