### ISSUE TITLE
time-order and indices

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#298]
So I realized that everywhere in the `acoustic` and `tti` wrapper there is : 
```
u = TimeData(name='u', shape=self.model.shape_domain,
                         save=save, time_dim=self.source.nt,
                         time_order=self.time_order,
                         space_order=self.space_order,
                         dtype=self.model.dtype)

```
`time_order` is supposed to be allways set to `2` for the wavefield. I don;t know when this changed but it now creates weird time loop indices as it set temp `t` for `t+2` and `t-2`.

Also, the Buffered indices are now `time, time+1, time+2` instead of `time-1, time, time+1`.

**Comment by mlange05** [comment]
Ok,
a) It would be really good if you could explain why the wavefield has to be 2nd order, even for the 4th order scheme. There are no annotations in the code that state this, so it is really easy to miss. 
b) We're testing with 4th order time - why are none of the tests triggering on this?

**Comment by mloubout** [comment]
for a)
http://www.sciencedirect.com/science/article/pii/S0168927406001012?via%3Dihub

Mainly, 4th order taylor is unconditionaly unstable so
- apply d/dt^2 to the wave equation
- replace some terms
- end up with a double laplacian but no 4th order time derivative
- still 4th order in time
b)
tricky, mix of 4th and 2nd order everywhere

**Comment by mloubout** [comment]
>Also, the Buffered indices are now time, time+1, time+2 instead of time-1, time, time+1.

any update?

For the 4th order I'm looking into fixing it in a nice way.

**Comment by FabioLuporini** [comment]
This commit/line **could** be the cause: https://github.com/opesci/devito/pull/293/commits/39afb019b853b1f3ec97394d554d13e23890b45a#diff-a106a375c221953a1c637f16ecad1c9eR557

**Comment by mloubout** [comment]
>Also, the Buffered indices are now time, time+1, time+2 instead of time-1, time, time+1.

Turns out, I made that change, this is to make sure modulo don't get caught in weird behavior forcing any modulo-ed index to be positive.

I'll try to make the 4th order as a "special kernel" the way TTI is handled as soon as I find time to do it.

**Comment by FabioLuporini** [comment]
@mloubout fixed?

**Comment by FabioLuporini** [comment]
@mloubout fixed?

**Comment by mloubout** [comment]
Yes by #473, closing
