### ISSUE TITLE
Point data time looop

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#299]
So a little issue I found.

The PointSource operation are separated from the main time loop in one case.

```
u[t, idx...] = u[t, idx...] + something
```
works good, but
```
u[t, idx...] = something
```
doesn't 

I created the branch `point-assign` to test it, `acoustic_example` is set up to use the new `assign` function that does `u[idx_rec] = rec`.

Sorry it is part of the wave-examples, I couldn't figure out how to add a trivial test, I have no idea what's going on in the `test_point_data.py`.

**Comment by FabioLuporini** [comment]
@mloubout I pushed a potential fix to the `point-assign` branch which seems to work, can you test it? Can you also check whether it passes all other tests? 

You can probably cherry-pick my commit on any branch you like, it's just a two lines change

**Comment by mloubout** [comment]
Your commit seems to fix it yes, thank you. Can you add it to your PR?

**Comment by FabioLuporini** [comment]
I'll file it in a different PR because I wanna test it properly. Meanwhile, do you mind keep staying on top of it -- just in case you encountered other problems?
I'll keep you posted

**Comment by mloubout** [comment]
Ok

**Comment by FabioLuporini** [comment]
PR #306 hopefully fixes this
