### ISSUE TITLE
dse/dle bug

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#304]
So I created a branch called dse-dle-bug that highlights some of the current issues I found.

There is an example file called `bug-ex` in `examples/seismic/acoustic`
The corresponding operator is `forward_bug` in `operators`.
The kernel is the combination
```
stencils = [stencil(u), stencil(dux), stencil(duy)] #  3 different coupled PDE stencils
stencils += src.inject(u) # inject src in u
stencils += rec.interpolate(u) # read rec in u
```

Issues for the three stencils as `[stencilu, stencildux, stencilduy]` :
- dle=dse='advanced` => two last stencils removed from the code
- dse='noop, dle='advanced' => two last stencils  removed from the code
- dse='advanced, dle='noop' => two last stencils removed from the code
- dse='noop, dle='noop' => two last stencils  removed from the code

Issues for the three stencils as `[stencildux, stencilduy, stencilu]`  and  `[stencilduy, stencildux, stencilu]` :
- dse='noop, dle='noop' => OK
- dse='noop', dle='advanced` => dle fails and crashes
- dse='advanced', dle='noop` => OK
- dle=dse='advanced` => dle fails and crashes

**Comment by FabioLuporini** [comment]
> dse='noop, dle='noop' => two last stencils removed from the code

This is a symptom this issue has nothing to do with dse/dle. I'll be looking into it

**Comment by FabioLuporini** [comment]
PR #306 hopefully fixes this

**Comment by FabioLuporini** [comment]
@mloubout we cal close this, right?

**Comment by mloubout** [comment]
fixed, closing
