### ISSUE TITLE
Messy parameters derivation in operator.py

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#318]
*** Some of the following may be debatable or I may be missing something ***

``parameters`` computed twice in ``Operator.__init__``. 

Also, for ``self.symbolic_data``, we could do the following:
- we already have a ``self.output`` attribute; we could then add ``self.input``
- infer ``self.symbolic_data`` from these two
This seems more natural to me

~Finally, we're doing: 
``parameters = list(set(parameters + dims_parents))``
but this breaks deterministic ordering (because of ``set``), which is a problem in the case of MPI execution and operator caching (though these features are still unused)~

~I'm temporarily marking this as a bug because of this last item~
EDIT: fixed

**Comment by FabioLuporini** [comment]
Reminder: `operator._extra_arguments` can/should be dropped. All arguments should naturally end up in `parameters`

**Comment by FabioLuporini** [comment]
Reminder: some methods suffixed with ``args`` other with ``arguments``

**Comment by FabioLuporini** [comment]
Reminder: in the constructor, we're computing both ``dimensions`` and a bit later ``dims``, which should just be the same

**Comment by FabioLuporini** [comment]
@mlange05 BTW, if you really find the time to revisit the derivation logic in ``operator.py.__init__``, here's a list of known things to look at. Ignore the first comment though ("Reminder: ``operator._extra_arguments`` can/should be ...")

**Comment by navjotk** [comment]
Can we have an updated, definitive TODO list here?

**Comment by FabioLuporini** [comment]
I'd say let's start with avoiding computing same information twice (look up ``parameters``, ``dimensions``, ``dims``, ...etc)

**Comment by FabioLuporini** [comment]
I don't have a definitive tODO list -- I've been using this issue to keep track of the things that we need to do, in random order

**Comment by navjotk** [comment]
> though these features are still unused

Non-existent would be more accurate?

> I'm temporarily marking this as a bug because of this last item

I believe this is fixed so this issue shouldn't be a bug any more. 

I'll wait for you to get an updated, definitive TODO on this before I get started specifically on this issue.

**Comment by FabioLuporini** [comment]
> I believe this is fixed so this issue shouldn't be a bug any more.

Yes, changed to enhancement

I think I provided enough information here to understand what needs to/could be done. I can otherwise do this once I'll be back from holidays.

**Comment by FabioLuporini** [comment]
I'm quite happy now about this, so closing ( @navjotk )
