### ISSUE TITLE
numerics of acoustic with constant velocity 

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#328]
We get segfaults when denormal numbers are dropped by the DLE. This seems to be a bug of GCC; things works like a charm with ICC. Hence, we're currently using the ``dle=advanced-safemath`` mode, rather than ``dle=advanced``. This needs to be investigated further.

**Comment by mloubout** [comment]
I played wit it and I am not able to reproduce it even with GCC, Will keep digging.

**Comment by mloubout** [comment]
Looks like fixed, no issue with #377, closing
