### ISSUE TITLE
Interfaces.py is too prone to circular dependencies

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#334]
While working on #332 we realised that there are several scenarios that lead to circular dependencies which can be traced back to how bulky `interfaces.py` has become. This file should (probably) be broken down into smaller parts so that the parts can individually be imported without creating circular dependencies.

**Comment by navjotk** [comment]
My last comment on the PR was that it does not address this issue. I'm not sure closing the issue was the best thing to do after that?

**Comment by FabioLuporini** [comment]
I don't think we have circular dependencies anymore. I think we should keep this open iff we are aware of at least one particular scenario in which there would be circular deps

**Comment by navjotk** [comment]
This issue was about a circular dependency between `memory.py` and `operator.py` via `interfaces.py` and nothing has changed in regard to that. That persists as far as I can tell: https://github.com/opesci/devito/blob/master/devito/memory.py#L81

Did I miss something?

**Comment by FabioLuporini** [comment]
Ah, I thought the issue was that you couldn't import `configuration` w/o creating a circular dependency, which forced you to add a global environment variable to `interfaces.py`

**Comment by navjotk** [comment]
I think this can be closed.

**Comment by FabioLuporini** [comment]
happy to close it
