### ISSUE TITLE
Interface needs cleanup and robustness rewrite

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#337]
To make it simple, we currently consider that any dimension except the first one is a spatial dimension (in `TimeData`) which make it a pain if you add a dimension. e.g if you solve multiple PDE at once in 2D you have `u[t,x,y,p_src]` but Devito interpret it as a 3D field and tries to take `u.dz2` in the laplacian.

This one should be "easy" as long as we consoder only 2 or 3D problems. If not, I need to reqrite `Dimension` to seperate spatial, temporal and local ones.

**Comment by chuckyount** [comment]
FYI, I had this problem in YASK. In the new version of YASK under development, I'm requiring the user to more explicitly create each dimension as 'step' (i,e., temporal), 'domain' (i.e., spatial), or 'misc' (i.e., local). This allows me to have grids like you have mention here, and mix 3d, 2d, and 1d grids in the same problem, like when using Cerjan arrays for ABC.

**Comment by FabioLuporini** [comment]
> if you solve multiple PDE at once in 2D you have u[t,x,y,p_src]

Can you please elaborate? What value is the notation ``u[t,x,y,p_src]`` trying to access?

**Comment by mloubout** [comment]
>What value is the notation u[t,x,y,p_src] trying to access?

The wavefield for the source number `p_src`, instead of looping over sources in python you solve all at once

**Comment by mlange05** [comment]
Yes, the new auto-generation of derivative shortcuts should allow this. It's currently ownly restricted to space, but I'm working on time.

**Comment by mloubout** [comment]
PointData is hard-coded as time-dependent, and non-compatible with non-conventional dimensions

**Comment by mloubout** [comment]
Open #374 for the pointdata part, this one can be closed I think wiht #369

**Comment by FabioLuporini** [comment]
Is this still an issue @mlange05  @mloubout

**Comment by mloubout** [comment]
Yes, I need to rewrite the "time free" case for the new devito.

**Comment by mloubout** [comment]
FIxed, closing.
