### ISSUE TITLE
Code quality issues related to checkpointing work

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#344]
This issue is to keep track of things being put off for until after checkpointing is completely in. 

~https://github.com/opesci/devito/pull/342#discussion_r137460092~

~https://github.com/opesci/devito/pull/342#discussion_r137458662~

~https://github.com/opesci/devito/pull/342#discussion_r137459227~

~https://github.com/opesci/devito/pull/342#discussion_r137457801~

~https://github.com/opesci/devito/pull/342#discussion_r137449295~

Edit: 

~https://github.com/opesci/devito/pull/354/files/324bdaf2843f577032f8604a0b1de3d09d5f6cf4#r141003338~

**Comment by FabioLuporini** [comment]
ANy leftovers here, @navjotk ?

**Comment by FabioLuporini** [comment]
Any leftovers here, @navjotk ?
