### ISSUE TITLE
Examples cleanup

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#358]
- Have a single ``ArgumentParser``, used by both acoustic and TTI and any other future seismic equations. Perhaps to be moved to a ``utils.py`` module under ``examples/seismic``
- Use memoization in acoustic, in the same way we did for TTI
- Move legacy leftovers of the following sort to ``model``:
```
    # 3D preset parameters
     if args.dim2:
        shape = (150, 150)
         spacing = (15.0, 15.0)
         tn = 750.0
     else:
        shape = (50, 50, 50)
        spacing = (20.0, 20.0, 20.0)
        tn = 250.0
```

**Comment by mloubout** [comment]
On it

**Comment by FabioLuporini** [comment]
Also:
- raise an error if one passes an non-existing model name to ``demo_model()``. I just bumped into this issue

**Comment by mloubout** [comment]
`demo_model` where is this one coming from?

**Comment by FabioLuporini** [comment]
as I wrote above, my mistake. However, you could still improve the ``demo_model`` docstring in ``examples/seismic/model.py``, as it still shows a description for ``layer2d`` and ``marmousi2d`` that are now unrecognised names.

Thanks

**Comment by mloubout** [comment]
We can close this no?

**Comment by FabioLuporini** [comment]
once #360 is in?

**Comment by FabioLuporini** [comment]
Done, closed
