### ISSUE TITLE
Verison for pip

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#362]
Shouldn't the version in the `setup.py` be the stable release one (like v3.0.3 currently) instead of latest master?

**Comment by mloubout** [comment]
ping

**Comment by mlange05** [comment]
Sorry for the delay in answering. And the short answer is no, `setup.py`/`pip` should always install the latest version unless this is specified like this: 
`pip install git+https://github.com/opesci/devito.git@v3.0.3`. 

The `versioneer` package we are using should also always make sure that the version string you get is effectively `<last_tag>+<commit_hash>` for all commits that are not tagged themselves.

**Comment by mloubout** [comment]
>setup.py/pip should always install the latest version unless this is specified like this

I know it does, I was asking if this is what we want, stable released version are more manageable in my opinion and seems to be the case for a lot of packages

**Comment by FabioLuporini** [comment]
can we close this?

**Comment by FabioLuporini** [comment]
I think we can close this. @mloubout

**Comment by FabioLuporini** [comment]
reminder

**Comment by mloubout** [comment]
I guess can be closed.
