### ISSUE TITLE
dse: Improve aliases detection

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#367]
If there are two expressions such as:
```
A = 0.05*v[t, x, y, z + 2] + 0.05*v[t, x, y, z + 5]
B = 0.05*v[t, x, y, z + 3] + 0.05*v[t, x, y, z]
```
then they won't be detected as aliases *iff* they are compared in the following way:
- A's first indexed (``v[t, x, y, z + 2]``) with B's first indexed (``v[t, x, y, z + 3]``) **and** A's second indexed (``v[t, x, y, z + 5]`` with B's second indexed (``v[t, x, y, z ]``).

However, if the comparison is swapped (A's first indexed with B's second indexed **and** A's second indexed with B's first indexed), then a common distance along ``z`` is determined (2) and A and B are detected as aliases.

The aliases detection engine should be improved and become independent of the order in which the indexeds with common coefficients (0.05 in this case) are returned by ``retrieve_indexed``. Perhaps do some sort of deterministic ordering?

This, however, only appears in TTI SO=16 with kernel=shifted.

The price to pay are more flops and more memory consumption (w.r.t. to cases in which things work smoothly, such as SO={4, 8, 12})

**Comment by ggorman** [comment]
This has gone through several revisions already; most recently in https://github.com/opesci/devito/pull/816
