### ISSUE TITLE
result of test_gradient.py 

### ISSUE THREAD

**Issue by dellabear** [opesci/devito#379]
Dear developers,

Currently, I am running the tests provided by devito. There are two functions in test_gradient.py.
The **test_gradientJ** has a reasonable result, but the result of test_gradientFWI has _0.9xxx_ order for both 1st order error and 2nd order error.

I don't know it is a code issue or the methodology issue.

**Comment by mloubout** [comment]
I do not seem to be able to reproduce this error.
Did you change anything to the script? And if no, could you please provide the log for the failing test.

**Comment by dellabear** [comment]
Thank you very much for your prompt reply. I figure it out. Thank you very much!

Best regards,
Yunan

**Comment by mloubout** [comment]
Great, closing issue.
