### ISSUE TITLE
verify is too specific

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#393]
So this issue is a bit odd, and I don't have and answer for it, just wanted to point it out for the future.

The point is, we moved to "generalized" generated code that accept any input as long as you know what the name is, however, in practice, calling an operator with say `op.apply(rec=rec2)` where `rec2` has one more receiver (coordinates has one more line) will fail as the array size don' match even if all symbolic object do.

I have nothing against generalised code, but there is not point to it if it is only callable with a single (and therefore easy to hardcode) set of input.

**Comment by mlange05** [comment]
Sounds like a bug in dealing with `CompositeFunction` arguments. Can you provide an MFE and assign to @navjotk, please?

**Comment by mloubout** [comment]
`rec` was an example, it extends to any of out Symbolic objects

**Comment by mlange05** [comment]
I don't think the generalisation holds: if I modify one of our existing arguments tests slightly to force a replacement of a symbolic object with one of another shape, it still runs fine (original in `test_operator.py`:
```
    def test_override_symbol(self):
        """Test call-time symbols overrides with other symbols"""
        i, j, k, l = dimify('i j k l')
        shape = (3, 5, 7, 6)
        a = symbol(name='a', dimensions=(i, j, k, l), shape=shape, value=2.)
        a1 = symbol(name='a1', dimensions=(i, j, k, l), shape=shape, value=3.)
        a2 = symbol(name='a2', dimensions=(i, j, k, l), shape=(3, 5, 7, 8), value=4.)
        op = Operator(Eq(a, a + 3))
        op()
        op(a=a1)
        op(a=a2)

        assert(np.allclose(a.data, np.zeros(shape) + 5))
        assert(np.allclose(a1.data, np.zeros(shape) + 6))
        assert(np.allclose(a2.data, np.zeros((3, 5, 7, 8)) + 7))
```

Admittedly, this should be added to the test base, of course.

**Comment by mloubout** [comment]
This one doesn't follow current convention or Devito object (no idea if it matters just pointing out). I will make a branch with fialing tests asap (after tuto nightmare), but it does fail at least for different sized PointData

It may be irrelevant (and for another issue) but this kind of setup shouldn't exit in out test-suite. We have Devito types and it should be the ones tested.

**Comment by mlange05** [comment]
> This one doesn't follow current convention or Devito object (no idea if it matters just pointing out). 

Again false (at least partially): explicit `shape`/`dimension` pairs are still allowed and needed for customization (I'm assuming that is what you are referring to). The only thing that has changed is that the convenience defaulting of dimensions has moved up a level, to the `Grid`, since it makes more sense for cases that primarily consider loops over traditional space and time constructs. In any case, it should be irrelevant to this problem. 

> but it does fail at least for different sized PointData

As I said, most likely a bug in the `CompositeFunction` handling during argument derivation. Additional tests are always welcome.

**Comment by mloubout** [comment]
>I'm assuming that is what you are referring to

My bad, overloading `symbol` for Devito ` Function` was confusing, though it was calling sympy directly. (still think it;s confusing and should be renamed)

I guess this issue can be closed and discussed internally to make sure "generanlized" code doesn;t fail for weird input.

**Comment by mlange05** [comment]
> My bad, overloading symbol for Devito Function was confusing, though it was calling sympy directly. (still think it;s confusing and should be renamed)

Lolz, that I totally agree with.

> I guess this issue can be closed and discussed internally to make sure "generanlized" code doesn;t fail for weird input.

How about renaming and adding a MFE for the `SparseFunction` failure you described?

**Comment by mloubout** [comment]
Just tested new API with different shape and seems to work, I guess `start/end` fixed, will open new issue if I stumble upon ne problem.

Sorry for wasting time.

**Comment by mloubout** [comment]
Renaming wrapper in the `test_operator` still should be done to avoid confusion.
