### ISSUE TITLE
Testing on travis on when needed

### ISSUE THREAD

**Issue by pp1336** [opesci/devito#41]
Hi guys, I am just thinking that we should not test very single push, but only the commit just before a PR merge? We seems to be the choking the server.

I am not familiar with Travis, is there way to set this up in Travis may be we should add [ci skip] in all but commits that are to be merged?

**Comment by mlange05** [comment]
I don't like this. I routinely use travis to run the full test suite and catch bugs this way, since running everything locally takes way too long.

**Comment by navjotk** [comment]
This choking the server observation is new. What makes you conclude that? Do you mean that the build queue is too long?

**Comment by pp1336** [comment]
quite a number of commits pushed are in the middle of development, this often delay checks for commits that are actually to be merged.

**Comment by mlange05** [comment]
Is this problem persisting? If so, I don't see any other way than trimming the test base itself, since regular Travis testing is an integral part of feature development. If not, can we close this please?

**Comment by pp1336** [comment]
I believe it happens sporadically when multiple of us are pushing.
