### ISSUE TITLE
YASK: call set_rank_domain_size at apply time

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#419]
Otherwise operator application will fail if trying to run on a smaller/larger grid

**Comment by FabioLuporini** [comment]
@tjb900 Could you upload a reproducible failing case for this? This is the very last thing we discussed at SC

**Comment by tjb900** [comment]
Sure!

[devito_issue419.tar.gz](https://github.com/opesci/devito/files/1489327/devito_issue419.tar.gz)

**Comment by FabioLuporini** [comment]
Closing as fixed by #434
