### ISSUE TITLE
Generic symbolic dimensions  

### ISSUE THREAD

**Issue by mlange05** [opesci/devito#43]
The default symbols used to represent the different spatial and temporal dimensions work fine for our current examples and test cases, but restrict users that may want to implement other, more complicated equations or time-stepping schemes. A more dynamic and customisable approach will facilitate further implementations and should allow us to significantly reduce the complexity of the `Propagator`. This, however, requires careful design which can be discussed in this issue.

My current thinking is based around the idea of introducing some type of `Dimension` class that, similar to our `SymbolicData` objects, associates SymPy dimension symbols (`x`, `y`, `z`, `t`) with meta-data about dimension sizes and loop iteration spaces. Such a model might work something like this:
- A Propagator maintains a list of `Dimensions`, which it can query to generate the appropriate C loop code, reducing the complexity of the Propagator code.
- A `Dimension` might yield multiple `IterationSpace` objects that represent sub-loops for loop blocking. These can be created according to various blocking schemes and across multiple dimensions.
- Individual stencil equations coming into the Operator can be scanned for `Dimension` symbols, which allows us to capture _free and bound variables_ and will allow us to automatically insert the stencil at the right depth in the loop nest. This will help with sanity checks for _operator merging_ and inserting sparse operations, ie. source and receiver terms, more gracefully.
- Additional SymPy expressions might be used to define custom stepping schemes for individual iteration spaces, which will allow user to implement custom time-stepping algorithms.

As stated above, this issue is intended for discussing and drafting a possible implementation, so comments and suggestions are highly welcome.

**Comment by vincepandolfo** [comment]
Should a `Dimension` object represent a loop on top of the ones defined by the `Iteration` objects?

If yes, I was thinking of a structure like this:
 - `self.iterations` list of `Iteration` objects for the sub loops
 - `self.stencils` list of stencils with the main code for the Dimension loop
 - `self.pre_loop_stencils` list of stencils to be executed before the dimension loop
 - `self.post_loop_stencils` list of stencils to be executed after the dimension loop

**Comment by mlange05** [comment]
No, a dimension in this case is a purely symbolic object that represents an iteration space, ie. `x` or `y` or `t` in our current examples. Thus it behaves like a symbol that we we use to index our symbolic data / function objects, but it knows about the bounds in a certain spatial dimension for example, including things like padding layers. As such it would be able to generate `Iteration` objects that represent actual loops in the code over a certain iteration space.

The core idea I am pursuing with this is that if our function indices are smart enough, we can simply pull all the free indices out of a stencil expression and generate the loop objects that each expression needs to encapsulated in. Once we know that and we get the data dependencies between variables, we can match loops/iteration spaces and thus auto-generate the exact loop nest require, without the need to pre-define loops like `pre_loop_stencils` or `post_loop_stencils`.

**Comment by mloubout** [comment]
`self.stencils` list of stencils with the main code for the Dimension loop
It still would be good to be able to have possibility to split the stencils in different dimension loop with intermediate `Pre/post` loops

**Comment by mlange05** [comment]
Ok, so I believe PR #156 brings us a good step closer to doing this in a much nicer way. After that all that is missing, at least as far as dimension handling is concerned, is the ability to switch between loops with open or pre-defined "baked in" limits at will (preferably by setting limits on the dimension objects).

**Comment by mlange05** [comment]
The new 3.0 API allows generic switching between pre-defined and open loop bounds, so I think we got all of this now in. So closing...
