### ISSUE TITLE
DEVITO_LOGGING doesn't seem to be respected

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#438]
The log level in master is set to WARNING but Travis logs still show log messages that shouldn't show up at that level.

**Comment by navjotk** [comment]
This is traced to `test_autotuner.py`. [This](https://github.com/opesci/devito/blob/master/tests/test_autotuner.py#L62) is an example but this is done in multiple tests in this file. Fix coming soon.

**Comment by FabioLuporini** [comment]
great

**Comment by mlange05** [comment]
Looks like the AT tests are forcing a temporary drop in debug level and re-instating the default instead of the previous log-level:
https://github.com/opesci/devito/blob/master/tests/test_autotuner.py#L36

If only we had a utility to do that in a more pythonic way :snake: ... something like the decorator in #429, maybe? :wink:

**Comment by mlange05** [comment]
I also note in passing that the logger interjection in those tests looks quite horrific, IMHO. Can we think of a better way to test the AT behaviour without relying on log string?

**Comment by FabioLuporini** [comment]
I'm not sure how to, I'm checking that the Operator is actually invoked as many times as expected, and the output data isn't available after AT execution, so... I'm all ears for suggestions! Perhaps I'm missing some obvious way?

**Comment by mlange05** [comment]
> and the output data isn't available after AT execution

Well, I guess if the AT is truly stateless, that's as far as we can go... :frowning: Anyway, not the source of the problem, just visually annoying.

**Comment by navjotk** [comment]
Fixed by #442 . Closing.
