### ISSUE TITLE
Reference for TTI example

### ISSUE THREAD

**Issue by shahir87** [opesci/devito#452]
I would appreciate if reference can be given for the tti seismic modelling example.
This will help to see how the equation is programmed in devito.

**Comment by FabioLuporini** [comment]
@mloubout

**Comment by shahir87** [comment]
I think the equation for TTI modelling used is from here: A stable TTI reverse time migration and its implementation (Zhang et al, 2011) from GEOPHYSICS, VOL. 76, NO. 3 (MAY-JUNE 2011); P. WA3–WA11.

The only problem is only Dx is defined for Gxx in this paper.

I see from the TTI examples, Dy and Dz are defined. I would appreciate if it can be shared why Dy and Dz are defined as such.

**Comment by FabioLuporini** [comment]
Perhaps it's enough to define a single derivative operator because in the other spatial dimensions they would be the same?

**Comment by shahir87** [comment]
[1-s2.0-S0098300416304034-main.pdf](https://github.com/opesci/devito/files/1547488/1-s2.0-S0098300416304034-main.pdf)
I found this paper on Devito, in Appendix there is wave equation for TTI modelling. Maybe this is the one? Complete Gxx, Gyy and Gzz are provided here.

**Comment by mloubout** [comment]
We have the equation from 
(Zhang et al, 2011) from GEOPHYSICS

and Dy and Dz are defined the same way as Dx, which is such that you get back Fletcehr fro constant theta/phi, just need to apply rotation matrix to dx, dy, dz

**Comment by shahir87** [comment]
Thanks @mloubout  and @FabioLuporini. I will read further on rotation matrix to understand it. I have read also Fletcher paper (2009).

**Comment by FabioLuporini** [comment]
Thanks @shahir87 . I'm closing this issue. If you have further queries of this sort, you're more then welcome to join our Slack channel (there's a #questions channel there and it's probably quicker to get answers!). To join it, follow the link at the top-right here: www.opesci.org
