### ISSUE TITLE
Src/Rec positions

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#48]
We need to remove the hard coding of the source/receiver position and reading/injecting the field. The way it currently is done works fine for small geometries, but involve re-generation of the code for every source. This is a cheap part of the computation so we can afford to replace this (40-100k lines) hardcoding with a few inputs and a general src/rec injection/read function allowing to generate and compile  the code only once.

For example, I am running a test model of size 201 x 201 x 70 , quite small, that should run within a couple minutes, however with 40000 receivers, the compiler takes forever (already 20min of cc1plus and still no sign of even starting to run).

**Comment by mloubout** [comment]
`33:16.00 cc1plus`

**Comment by mloubout** [comment]
@ggorman @navjotk @mlange05 
This issue as to be top priority, we can not run any realistic/convincing 3D examples currently. Let me know how you think we should handle it and what I can do to help.

**Comment by mlange05** [comment]
Was this solved sufficiently by PR #59?

**Comment by mloubout** [comment]
I think it was, I successfully generated code for 375^2 receivers in an ok time and compiled. More flexible src/rec will be a problem for later once our UBC people write properly what they want to do.

**Comment by mlange05** [comment]
Ok, cool. In that case I'm closing this. 

The more advanced src/rec should become easier once we merge PR #92 and after some further work on issue #43 (after all, `p` is just another dimensions with indirect data and a defined iteration space).
