### ISSUE TITLE
Trivial test produces float indices?

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#492]
I was really thrown by this one.  Hitting it on today's master (ce3ed62f1b), but it appears to be there in many previous versions (I tried random commits back to Dec).  I don't know how I haven't come across it before...

```
from devito import Operator, TimeFunction, Grid
from sympy import Eq, solve

def test_reallybasic():
    grid = Grid(shape=(50,50), extent=(1,1))
    u = TimeFunction(name='u', grid=grid, space_order=4,time_order=2)
    step = Eq(u.forward, solve(Eq(u.dt2,0.25*u.laplace),u.forward)[0])
    op = Operator(step)

    u.data[:] = 0.0
    u.data[25,25] = 1.0
    op.apply(time=2)
```

Among other similar errors:
```
/localData/000scratch/devito-kp3l4yb4/408dcd2630a540e82b01247ae233e9f2dbfb47ab.c(31): error: expression must have integral type
          u[t1][x][y] = 2.08333333333333e-2F*((dt*dt)*(h_x*h_x)*(tcse0 - (u[t0][x][y - 2.0F] + u[t0][x][y + 2.0F]) + 1.6e+1F*(u[t0][x][y - 1] + u[t0][x][y + 1])) + (dt*dt)*(h_y*h_y)*(tcse0 - (u[t0][x - 2.0F][y] + u[t0][x + 2.0F][y]) + 1.6e+1F*(u[t0][x - 1][y] + u[t0][x + 1][y])) + 4.8e+1F*(h_x*h_x)*(h_y*h_y)*(2.0F*u[t0][x][y] - u[t2][x][y]))/(pow(h_x, 2)*pow(h_y, 2));
```

Notably terms like:
```
u[t0][x][y - 2.0F]
```

**Comment by mloubout** [comment]
This is not a Devito issue but due to how `sympy.solve` works, you should be good with `solve(Eq,. rational=False)`.

**Comment by tjb900** [comment]
Cheers!

**Comment by mloubout** [comment]
> I've just never needed that before

I am still not sure when it does/does-not happens, `solve` seems quite random at times, so I now always force `rational=False, simplify=False`. The second one avoids spending half an hour in `solve` for some more complex PDE and thinking Devito has a problem.

**Comment by FabioLuporini** [comment]
maybe we could provide our own version of ``solve`` that adds in those flags automatically

**Comment by tjb900** [comment]
I'm leaving this open, as one day I hope to get to making a PR to actually prevent us from generating float indices.

**Comment by FabioLuporini** [comment]
@mloubout do we still want to provide our own ``solve``? I think so. If you add it, perhaps you want to place it in ``finite_differences.py`` ?

**Comment by mloubout** [comment]
Yesm it's still in #484 but I need to fix and cleanup sparese-fd first.

**Comment by tjb900** [comment]
Hmmm, thought I replied to this.  I think it can be closed  - I haven't hit it in quite a long time now.  Hopefully this is not just because of `solve`.

**Comment by FabioLuporini** [comment]
OK, closing, feel free to reopen if you bump again into anything similar
