### ISSUE TITLE
Installation failed using recommended conda method

### ISSUE THREAD

**Issue by L4student** [opesci/devito#495]
Hello. I am trying to install devito, but I get errors that suggest `Failed to build multidict` and `NameError: global name 'FileNotFoundError' is not defined` as shown in the [attached log file](https://github.com/opesci/devito/files/1742154/error_install.log) from installation. 

My conda versino is `4.3.29` with `Python 2.7.13`, on a linux machine with `16.04.1-Ubuntu`. 

I tried searching for any previous issue associated with this error, but couldn't find one. Could you suggest what may be the reason for this failure? Thanks.

**Comment by chuckyount** [comment]
Hi. I'm not on the DeVito team, so take this for what it's worth, but I believe it only supports Python 3.

**Comment by FabioLuporini** [comment]
@chuckyount is correct. You need the P3 version of conda. But thanks for pointing this out: I'll update the installation instructions accordingly. Let us know if we can close this issue.

**Comment by L4student** [comment]
Thanks, guys. It works now.
