### ISSUE TITLE
Coefficient varying with space and/or time

### ISSUE THREAD

**Issue by L4student** [opesci/devito#496]
Is there a provision in devito where a coefficient could be considered a variable in space and/or time instead of a constant value? For instance, is it possible to consider a diffusion coefficient (or any other coefficient that is generally assumed a constant) to be a variable in space and/or time? 

It's possible devito may already have this provision, in which case I apologize, but I couldn't find it based on my review of the examples. I also searched for any previous issue associated with this question, but I couldn't find one.

**Comment by mloubout** [comment]
Hi

I am not sure what you mean by coefficients. Do you mean the FD weigthts or the PDE coefficients.

In the second case, all the examples in `seismic` are for spatially varying velocity/anisotropy.

**Comment by L4student** [comment]
Hi. I mean the PDE coefficients. If you take a look at the diffusion equation in the following wikipedia article,  the diffusion coefficient `D` is not the main PDE variable, but it is allowed to vary in space and/or time. I think you can call `D` as PDE coefficient. However, in the case of the seismic wave equation, the velocity is a primary unknown variable and that is not what I meant.
https://en.wikipedia.org/wiki/Diffusion_equation

**Comment by mloubout** [comment]
>However, in the case of the seismic wave equation, the velocity is a primary unknown variable and that is not what I meant.

It is not possible to model a PDE with unknown parameter. The velocity is unknown in the seismic inverse problem, we however still solve the wave-equation for a given estimate of it.
To summarize, the wave-equation has spatially variable coefficients (all OT2, OT4 and TTI do), just follow the examples and tutorials.

**Comment by L4student** [comment]
Thanks. Although I see a spatially varying coefficient, please allow me to ask one related question: for spatially varying PDE coefficients do you implement upwinding in case of divergence term? For instance, in [convection-diffusion equation](https://en.wikipedia.org/wiki/Convection%E2%80%93diffusion_equation), the coefficient `D` is within the divergence term. The discretization of this divergence term with spatially varying `D` generally requires upwinding..

**Comment by mloubout** [comment]
The discretization is your choice.

**Comment by L4student** [comment]
Thanks.
