### ISSUE TITLE
TimeData not found

### ISSUE THREAD

**Issue by Cyberface** [opesci/devito#501]
Hi!

So I installed the latest devito and I'm trying to load the `TimeData` as I have seen in some tutorials but it seems that `TimeData` can not be found?!

```
from devito import *
?TimeData()
Object `TimeData` not found.
```

Am I doing something wrong?

Thanks!!

**Comment by mloubout** [comment]
`TimeData` does not exist in the latest release. The tutorial associated wit hthe latest devito use `TimeFunction`. Which tutorial still uses TimeData

**Comment by Cyberface** [comment]
Hi thanks for the reply!

I found this tutorial here: http://www.opesci.org/devito/heat.html
An old one I guess.

Could you also tell me if devito can be used for 1D ODEs?

**Comment by mloubout** [comment]
I don't know how you ended up at this page, the tutorials are here

http://www.opesci.org/devito/tutorials.html

It should work also in 1D.

**Comment by Cyberface** [comment]
OK thanks! I'm not sure I've seen any 1D tutorials anywhere? Are you able to point me to any?

Thanks!

**Comment by mloubout** [comment]
We did not made any 1D examples, but you should be able to make one following the 2D/3D ones.

**Comment by Cyberface** [comment]
ok thanks!

**Comment by FabioLuporini** [comment]
@Cyberface I'm closing this issue
