### ISSUE TITLE
openmp parallelism not produced under some circumstances involving subdims

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#508]
It looks like something is going astray in the detection of parallelism with the combination of `region=INTERIOR` and complex dependencies (as seen in e.g. Higdon boundaries).

This works:

```
from devito import (Grid, Operator, TimeFunction, configuration, Eq,
                    INTERIOR, DOMAIN)

configuration["openmp"] = True

grid = Grid(shape=(20,20))
x, y = grid.dimensions
t = grid.time_dim

u = TimeFunction(name='u', grid=grid, save=10, time_order=1)

steps = []
steps.append(Eq(u.indexed[t+1, x, y],
                u.indexed[t+1, x-1, y] + u.indexed[t, x, y], region=DOMAIN))
op = Operator(steps)

print(op)
```

producing:

```
    struct timeval start_section_0, end_section_0;
    gettimeofday(&start_section_0, NULL);
    for (int x = x_s + 1; x < x_e; x += 1)
    {
      #pragma omp parallel
      {
        #pragma omp for schedule(static)
        for (int y = y_s; y < y_e; y += 1)
        {
          u[time + 1][x][y] = u[time][x][y] + u[time + 1][x - 1][y];
        }
      }
    }
```

(though note that it would be presumably be faster with the x and y loops inverted?)

But when we use `region=INTERIOR`, the parallelism disappears:

```
    for (int xi = xi_s + 1; xi < xi_e; xi += 1)
    {
      for (int yi = yi_s; yi < yi_e; yi += 1)
      {
        u[time + 1][xi][yi] = u[time][xi][yi] + u[time + 1][xi - 1][yi];
      }
    }
```

**Comment by FabioLuporini** [comment]
> (though note that it would be presumably be faster with the x and y loops inverted?)

I think the compiler here is acting smartly; it detects a dependence in the ``x`` dimension due to ``u[time + 1][x][y]`` (LHS) and ``u[time + 1][x - 1][y]``, so it picks ``y``, which is a dependence-free loop

> But when we use region=INTERIOR, the parallelism disappears:

this one is odd; investigating

**Comment by FabioLuporini** [comment]
> this one is odd; investigating

Apparently this is getting fixed by your PRs

**Comment by tjb900** [comment]
> I think the compiler here is acting smartly; it detects a dependence in the x dimension due to u[time + 1][x][y] (LHS) and u[time + 1][x - 1][y], so it picks y, which is a dependence-free loop

Oh yeah, I understood why it did that.  That is pretty awesome.

What I meant by inverted was this, which doesn't start up/shutdown the parallel loop several times (but I know we can't do it yet):

```
    struct timeval start_section_0, end_section_0;
    gettimeofday(&start_section_0, NULL);
    #pragma omp parallel
    {
      #pragma omp for schedule(static)
      for (int y = y_s; y < y_e; y += 1)
      {
        for (int x = x_s + 1; x < x_e; x += 1)
        {
          u[time + 1][x][y] = u[time][x][y] + u[time + 1][x - 1][y];
        }
      }
    }
```

**Comment by FabioLuporini** [comment]
yeah, we cannot do it yet, but it's definitely a pass that we could add!
