### ISSUE TITLE
notebook describing op.apply

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#520]
We need a jupyter notebook explaining, perhaps with stupid examples, the mechanics of ``op.apply``. in particular:
* what it does:
** potentially triggers compilation
** potentially allocates data
**generation of default runtime values
** execution of code
* accepted parameters (semantics of *_m, *_M, *_n, ...)
* what else?

**Comment by beterraba** [comment]
maybe this is related to PR #624 ?

**Comment by FabioLuporini** [comment]
this question appeared on Slack:

> Just to check,  am I correct in thinking that when I run `op_dev = Operator([stencil_dev])` followed by `op_dev(time=timesteps, dt=dt)`, I am iterating my stencil by “timesteps” timesteps of size “dt”?

and here's my reply. We might reuse parts of it for the notebook we aim to write...

when you run an Operator, *ideally* you’d compute the timesteps in the compact interval `[time_m, time_M]`, where `m=min` and `M=max`. `time` is a mere shortcut for `time_M`. Now, depending on the actual equations  being computed (and therefore depending on things such as the time order of your fields and what time derivatives have you taken), the *actual* timestep interval may be slightly smaller, to avoid out-of-bounds array accesses.

For example, if your equation is:
```
f[t+1, x] = f[t, x] + 1
```
and you run it with
```
Operator(...).apply(time=10)
```
then you’ll iterate over `[0, 10]`, ie 11 iterations

if you instead run it with
```
Operator(...).apply(time_m=5, time_M=10)
```
then obviously it’ll be `[5, 10]`

However, consider now the following equation:
```
f[t+1, x] = f[t, x] + f[t-1, x]
```
Now the Operator cannot start at 0, as otherwise you’ll end up accessing `f[-1, x]`. So it will automatically set the iteration interval to `[1, 10]`.

Note that this applies seamlessly to *any* dimension (not just time).
And this is supposed to work even if your Operator has 1000 complicated equations etc.

Also note this: https://github.com/opesci/devito/issues/520 . We haven’t described how this works properly :slightly_smiling_face: so apologies if the documentation is missing or is incomplete.
I think that `print(Operator.apply.__doc__)` may provide additional information
