### ISSUE TITLE
extra occurrence of no parallelism using subdims

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#521]
Very similar to #508 , but with the flow dependence on `y` instead of `x`.

```
from devito import (Grid, Operator, TimeFunction, configuration, Eq,
                    INTERIOR, DOMAIN)

configuration["openmp"] = True

grid = Grid(shape=(20,20))
x, y = grid.dimensions
t = grid.time_dim

u = TimeFunction(name='u', grid=grid, save=10, time_order=1)

reg = INTERIOR

steps = []
steps.append(Eq(u.indexed[t+1, x, y],
                u.indexed[t+1, x, y-1] + u.indexed[t, x, y], region=reg))
op = Operator(steps)
```

Loops are parallel over `x` when `reg=DOMAIN`, but not with `reg=INTERIOR`.

Not fixed by #509 or #519.

**Comment by FabioLuporini** [comment]
yes, I have a fix in `fix-subdims`

In this branch, I added the parametrized test  ``test_dimension.py:test_iteration_properties`` which we should update as we find more subdimension/region-related tests breaking parallelism (hopefully converging to 0 soon)

**Comment by tjb900** [comment]
Ah, yes, I just pulled that branch and it works now.  Thanks :-)
