### ISSUE TITLE
notebook describing ConditionalDimension

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#549]

**Comment by btrb** [comment]
Maybe this is related to PR [#671](https://github.com/opesci/devito/pull/671)

**Comment by FabioLuporini** [comment]
why? do you do anything with ConditionalDimension in there?

**Comment by btrb** [comment]
not quite, but I mean like a continuation for what's going on in `/examples/compiler`
maybe from `03_halos` there might be a `04_conditional_dimension`

**Comment by FabioLuporini** [comment]
ah, yes, absolutely

**Comment by FabioLuporini** [comment]
done via #780 , so closing
