### ISSUE TITLE
dimension_sort behaving badly

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#559]
I think there are perhaps several issues here

#### 1. `partial_order` hangs when given some (impossible) ordering problems.

e.g.

```
from devito.tools import partial_order
partial_order([(1,2,3),(3,4,2)])
<hangs>
```

#### 2. Side issue, but relevant for creating a test: `dimension_sort` is nondeterministic.

This is due to the fact that `free_symbols` is not ordered in the following (`devito/symbolics/inspection.py`):

```
                constraint.extend([d for d in ai.free_symbols
                                   if isinstance(d, Dimension) and d not in constraint])
```

#### 3. `dimension_sort` can sometimes generate such impossible ordering problems.

Due to (1), this is catastrophic.  Due to (2), it's difficult to write a useful CI test for this.

Running the test below several times will illustrate the problem.

```
def test_dimension_sort():
    grid = Grid(shape=(10, 10))
    p = Dimension('p')
    r = Dimension('r')
    d = Dimension('d')
    time = grid.time_dim
    x, y = grid.dimensions

    a = Function(name='a', dimensions=(time, p), shape=(10, 1))
    b = Function(name='b', dimensions=(time, x, y), shape=(10, 10, 10))
    c = Function(name='c', shape=(1, 2),
                 dimensions=(p, d), dtype=np.int32)
    f = Function(name='f', dimensions=(p, r), shape=(1, 1))

    expr = Eq(a[time, p], b[time, c[p, 0]+r, c[p, 1]] * f[p, r])

    op = Operator(expr)
```

To save you adding the logging, the above results in one of the two calls below to `partial_order`.  The second one is one of the impossible hanging problems:

```
partial_order([(time, p), (p, r), (time, p, r)])
partial_order([(time, p), (p, r), (time, r, p)])
```

I think it's generating constraints which are too strict.  The lookup into `b` is what generates the `(time,p,r)` or `(time,r,p)` order constraint.  But I don't believe that part of the expression `(c[p,0]+r, c[p,1])` implies any necessary or desirable ordering between `r` and `p`.

**Comment by FabioLuporini** [comment]
> partial_order([(time, p), (p, r), (time, r, p)])

I can see that this will hang: it cannot satisfy ``p < r`` and ``r < p`` ('<' meaning precedence).

> But I don't believe that part of the expression (c[p,0]+r, c[p,1]) implies any necessary or desirable ordering between r and p.

Agreed.

I'll think about how to fix this

**Comment by tjb900** [comment]
> I can see that this will hang: it cannot satisfy p < r and r < p ('<' meaning precedence).

Yeah.  Although I think even in this case it should return the empty list rather than go into an infinite loop...
