### ISSUE TITLE
Dask hangs intermittently on travis

### ISSUE THREAD

**Issue by ggorman** [opesci/devito#574]
Work in progress in PR #573. PR should not be merged until its clear this issue is resolved.

**Comment by ggorman** [comment]
Potentially related to https://github.com/dask/distributed/issues/1628

**Comment by ggorman** [comment]
Potentially related to https://github.com/dask/distributed/issues/1952

**Comment by ggorman** [comment]
Hanging still observed after change to dask/distributed master.

**Comment by ggorman** [comment]
Just discovered tool trytravis - could this be the end of commit-debugging madness?

**Comment by ggorman** [comment]
Now being explored in #587.

**Comment by georgebisbas** [comment]
Does that issue need to be closed?

**Comment by ggorman** [comment]
This is essentially a Travis issue that is triggered by oversubscribing test nodes. See https://github.com/opesci/devito/pull/798 for resolution.
