### ISSUE TITLE
numpy 1.15 currently breaks Devito

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#608]

**Comment by navjotk** [comment]
Do we know what is the change causing this?

**Comment by navjotk** [comment]
If I understand correctly, this is actually a bug in numpy 1.15 as discussed [here](https://github.com/toinsson/pyrealsense/issues/82), and a (partial?) patch was offered and merged [here](https://github.com/numpy/numpy/pull/12431), which will probably be included in numpy 1.16 . 

So we either wait for 1.16 to be released and test this again then - if it doesn't work we report this back to the numpy developers. Of course, this could be pre-empted by trying out the current numpy master and possibly getting the numpy team to include an updated patch in 1.16 (assuming it's still the same bug that causes our failures).

**Comment by FabioLuporini** [comment]
this has been fixed by #747 , so closing
