### ISSUE TITLE
Time varying boundary conditions

### ISSUE THREAD

**Issue by arnabd88** [opesci/devito#616]
Is there a way to specify time varying boundary conditions in the stencils ? Suppose we have a boundary condition of cos(\pi * t), where 't' is the current time step. grid.stepping_time tracks the iteration delta, but is there a way to retrieve the actual execution step with respect to the start of execution.

**Comment by mloubout** [comment]
Hi

`grid.time_dim` will track the actual execution step

**Comment by FabioLuporini** [comment]
can we close this?

**Comment by arnabd88** [comment]
yes , that was helpful. It can be closed.
