### ISSUE TITLE
aliasing fixture in the devito testing infrastructure

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#634]
the ``pytest_fixture`` ``a`` is defined at least twice: once in ``conftest.py`` and then again in ``interpolation.py``. Depending on the execution order of the tests, this may lead to "false bugs". 
This really sucks. It's a mistake to pollute ``conftest.py`` with lots of symbols/dimensions/... to be shared by different tests. It also sucks that pytest registers two fixtures with the same name and doesn't complain

**Comment by ggorman** [comment]
Superseded by #764
