### ISSUE TITLE
Redundant OpenMP variable

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#64]
I am opening an issue because I can't figure out how to comment on code already in master. Since we moved the compilation to `compiler.py`, the OpenMP flag is being set from the env variable directly inside `compiler.py` (https://github.com/opesci/devito/blob/master/devito/compiler.py#L176). 

Why, then, does a variable with that name still exist in `operator.py`? https://github.com/opesci/devito/blob/master/devito/operator.py#L87

@mlange05

**Comment by mlange05** [comment]
Yes, looks like an oversight. I believe the correct way to address such things is submitting a PR that fixes them. :wink:

**Comment by sheino** [comment]
I have deleted that var in my auto_tuning branch as I saw that its not used. Is it alright if this fix goes with PR78 or should i revert the changes?
