### ISSUE TITLE
Failure to recompile upon (certain) parameter changes

### ISSUE THREAD

**Issue by rhodrin** [opesci/devito#658]
After running a devito model with a certain parameter set (i.e. `DEVITO_AUTOTUNING=off python myfile.py`), re-running the model with a modified parameter (i.e. `DEVITO_AUTOTUNING=aggressive python myfile.py`) results in an OSError:

```python
  File "/data/devito/devito/operator.py", line 435, in apply
    self.cfunction(*arg_values)
  File "/data/devito/devito/operator.py", line 233, in cfunction
    self._lib = load(self._soname)
  File "/data/devito/devito/compiler.py", line 317, in load
    return npct.load_library(str(get_jit_dir().joinpath(soname)), '.')
  File "/home/rhodri/anaconda3/envs/devito/lib/python3.6/site-packages/numpy/ctypeslib.py", line 157, in load_library
    raise OSError("no file with expected extension")
```
With certain parameter changes the variable `self._soname` is modified and hence `self._lib = load(self._soname)` (line 233 of operator.py) points at a new shared object. However, this shared object does not get created resulting in the OSError. This error occurs when any parameter modification results in a `self._soname` different from the previous compilation. 

This object is not created since the variable `recompiled`, computed in the `jit_compile` method of compiler.py, is returned as `False` upon such parameter changes. Hence, compiling and running then modifying any parameter that results in a new `self._soname` and re-running results in this error. 

Clearing the cache and then recompiling (which should always result in `recompiled=True`) is a workaround to this issue.

Modifying the function `compile_from_string()` such that it returns values of `True` following the modification of any parameter resulting in a new `self._soname` would seem an appropriate fix?

**Comment by rhodrin** [comment]
Oh, so I see `compile_from_string()` is not actually a Devito function which potentially complicates things a little?

**Comment by rhodrin** [comment]
I've now created a branch [fix_recompile](https://github.com/opesci/devito/tree/fix_recompile). This, along with a CodePy patch seem the cleanest way of solving this issue.

My suggested change is modifying, in [jit.py](https://github.com/inducer/codepy/blob/45dac0819f73f40c125eae2dbb435226d73b7ce3/codepy/jit.py#L294),

```python

    def calculate_hex_checksum():
        try:
            import hashlib
            checksum = hashlib.md5()
        except ImportError:
           ...
```

to

```python

    def calculate_hex_checksum():
        try:
            import hashlib
            checksum = hashlib.sha224(name.encode('utf-8'))
        except ImportError:
           ...
```

CodePy in its current form seems to have an issue when the same shared directory is used repeatedly?

Thoughts?

**Comment by FabioLuporini** [comment]
this should be fixed.
