### ISSUE TITLE
CFD tutorials: plot_field function fails on non-square grid

### ISSUE THREAD

**Issue by thast** [opesci/devito#666]
Playing with the Poisson tutorial and changing the grid to a non-square one, I get an error at the `plot_field` line.
![image](https://user-images.githubusercontent.com/13682747/46909330-5ee99880-cee5-11e8-9319-8ba7426eb10b.png)

Trying to debug it, we found out with @mloubout that the meshgrid is doing something something funny and the shape of the objects are not matching, with this code from the .py
![image](https://user-images.githubusercontent.com/13682747/46909348-a5d78e00-cee5-11e8-95bc-7bd89f04d62b.png)

Testing the shape in our case we get:
![image](https://user-images.githubusercontent.com/13682747/46909357-ce5f8800-cee5-11e8-8144-54d4a10eb6ed.png)
So the shape of X and Y are the reverse of the field object.

**Comment by georgebisbas** [comment]
Is that as simple as 
``` ax.plot_surface(X, Y, **np.transpose**(field[:]), cmap=cm.viridis, rstride=1, cstride=1,linewidth=linewidth, antialiased=False) ```

**Comment by mloubout** [comment]
Fixed in #697 closing
