### ISSUE TITLE
Staggered setup

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#693]
The main issue is that currently, and as expected, with staggered object, some fields have different size (1 point less/more in the staggered direction)

We need to add an extra one point to the halo so that all fields have same size and we don't have OOB. For some reason it doesn't break now as I think the smallest extent is inferred, however it means the last point is not computed for some fields.

**Comment by FabioLuporini** [comment]
thinking again about this, is it really true that we have OOB? don't we just have one extra **unused** point in staggered Functions ?

**Comment by mloubout** [comment]
I think this can be closed.

**Comment by FabioLuporini** [comment]
>  For some reason it doesn't break now as I think the smallest extent is inferred, however it means the last point is not computed for some fields.

any comments about this?

**Comment by FabioLuporini** [comment]
@mloubout I suspect this can be closed now?

**Comment by mloubout** [comment]
Yes, closing
