### ISSUE TITLE
Website: broken link to tutorial.

### ISSUE THREAD

**Issue by jhidding** [opesci/devito#700]
Hi,
The homepage has a broken link. Just below the teaser example of the heat equation, there's a link to the "full tutorial" that doesn't work. I could find the relevant material by following another link to the Sphinx pages (https://www.devitoproject.org/devito/tutorials.html). Otherwise Devito looks awesome and I can't wait to try it ;)
Cheers!

**Comment by georgebisbas** [comment]
Hello @jhidding can you copy-paste the link and the homepage you visited as well?
Thanks

**Comment by jhidding** [comment]
When visiting https://www.devitoproject.org/, the link currently points to https://www.devitoproject.org/devito/heat.html

**Comment by georgebisbas** [comment]
Thank you for the comment @jhidding . 
You are probably searching for this examples. 
The broken link will be fixed soon I hope!
Thanks!

**Comment by georgebisbas** [comment]
Can be closed.
