### ISSUE TITLE
Initialization of `SymbolicData` objects

### ISSUE THREAD

**Issue by vincepandolfo** [opesci/devito#71]
Since #67 brought to light some issues with the initialization of SymbolicData objects (TimeData objects specifically) we need to find a coherent and uniform interface to initialize SymbolicData objects.

A possible solution for TimeData would be to have the `data` property reference `_full_data` instead of `_data`. In this way when `self.initializer` is called from `initialize` it will get as an argument the full data array instead of the data array with the hidden indexes.

This would also have the effect of removing the time padding from the user point of view.

Initial discussion with @mlange05 here: https://github.com/opesci/devito/commit/09dc1557d51455c6be6fe6e887223e5d568282ee#commitcomment-18517910

**Comment by mlange05** [comment]
I like the idea of having the `data` property referencing `_full_data` under the hood for time-buffered `TimeData` objects. I also note that this probably aligns with issue #69, where the obvious solution is to keep a private running timestep counter that we can modulo on to get the right time-frame in `data`.

Also, I believe the idea of adding the "initializer function" as a constructor argument was floated at some point, which I think sounds like a good idea? As does the idea of removing the `pad_time` argument? Just a few suggestions for further discussion...

**Comment by navjotk** [comment]
Agree on the initializer function and `pad_time` above.

**Comment by vincepandolfo** [comment]
Having `data` reference `_full_data` doesn't quite work since `Operator.apply` calls `param.data`, but it needs `_data` to work since when `save=True` the generated code tries to access the hidden indexes.
