### ISSUE TITLE
Diffusion test looks incomplete

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#72]
In the code for the diffusion test, I see that  no time_dim parameter is being passed to the `TimeData` constructor [here](https://github.com/opesci/devito/blob/master/tests/test_diffusion.py#L126). I think the behaviour of the entire `TimeData` object is undefined in such a case and there should be an assert in the constructor to make sure we don't execute in case this happens. In the particular case of the diffusion example, I doubt this code is doing what the author meant it to do. 

Also, the [save test](https://github.com/opesci/devito/blob/master/tests/test_save.py#L25) which was inspired by this test actually fixes this.

**Comment by vincepandolfo** [comment]
`time_dim` is not used when `save=False`. So there is no problem with the diffusion test.

**Comment by navjotk** [comment]
True that. My bad.
