### ISSUE TITLE
Tutorials to substitute/update old ones.

### ISSUE THREAD

**Issue by georgebisbas** [opesci/devito#720]
Probably Jupyter notebook for https://www.devitoproject.org/devito/heat.html , and let’s put it under the main devito repo and run it with CI so that we’re sure it will always be up-to-date
We can also use this one: [01_modelling](https://github.com/opesci/devito/blob/master/examples/seismic/tutorials/01_modelling.ipynb) in place of the obsolete wave equation tutorial?
@FabioLuporini

**Comment by georgebisbas** [comment]
I wondering what is the advantage of having the example/tutorial embedded in the wiki of devito like [this](file:///home/gb4018/FORKS/devitoproject.github.io/devito/heat.html)  instead of just pointing to the desired one from examples like [this](https://github.com/opesci/devito/blob/master/examples/seismic/tutorials/01_modelling.ipynb).

**Comment by FabioLuporini** [comment]
none. We should have a new jupyter notebook for the heat equation and point to it directly

**Comment by georgebisbas** [comment]
So, as I also noted in my after-failed-message in weekly meeting the example `03_diffusion` in cfd can be used for the heat equation as it like that now [Info](https://physics.stackexchange.com/questions/165928/what-is-the-difference-between-the-diffusion-equation-and-the-heat-equation) I am thinking of using a non uniform constant to make it like one of these :
[Google image for non uniform heat equation](
https://www.google.com/search?q=heat+equation+for+non+uniform&client=ubuntu&tbm=isch&tbs=rimg:CZtR4LkCeRaYIjj7VEb-kWVxBZshU6YUjeOjfWEjwHLgGM2wpE41tbJC3WUlH5HADBCwyUdITl6viajW6gMT_10wZcyoSCftURv6RZXEFEZjqr9AXvtXNKhIJmyFTphSN46MR1PLsDD1W4IcqEgl9YSPAcuAYzRGH4AvMVdVKfSoSCbCkTjW1skLdETwGQDb3qvUuKhIJZSUfkcAMELARImWwtgM94aYqEgnJR0hOXq-JqBF-io_19V6RJayoSCdbqAxP_1TBlzETz_1E1wF4wpM&tbo=u&sa=X&ved=2ahUKEwiWspLMy-jeAhVkDsAKHfscAvkQ9C96BAgBEBs&biw=1873&bih=959&dpr=1)

**Comment by FabioLuporini** [comment]
that looks cool

**Comment by georgebisbas** [comment]
@FabioLuporini I think this issue can be closed as the objectives are complete. We may keep it if you think we should add new objectives.

**Comment by FabioLuporini** [comment]
ok, closing
