### ISSUE TITLE
Mac OS installation error

### ISSUE THREAD

**Issue by dekape** [opesci/devito#743]
Hi everyone!

Trying to install Devito on my machine I get an error that seems to be related to pytest. I get the following output from terminal: 
[installation_error_devito.pdf](https://github.com/opesci/devito/files/2710655/installation_error_devito.pdf)
My machine specs are:
macOS Mojave 10.14
2.2 GHz Intel Core i7
16 GB 1600 MHz DDR3 memory
and Intel Iris Pro 1536MB graphic card

Does anyone have an idea of why this might be happening? Cheers!

**Comment by btrb** [comment]
Hey dekape, try asking that on Devito's Slack.
There's an exclusive channel for problems with installation.

You can have yourself an invite through:
https://opesci-slackin.now.sh/

**Comment by btrb** [comment]
By the way, which installation method are you trying?
You can find installation instructions here:
https://www.opesci.org/devito/download.html

**Comment by btrb** [comment]
What happens if you type 
`pip install coverage`
?

**Comment by dekape** [comment]
Still couldn’t fix it, but all requirements seem to be correctly installed!

**Comment by FabioLuporini** [comment]
Mojave does something bad to the command line tools including gcc. Can you try wiping it out completely and then reinstalling it?

**Comment by FabioLuporini** [comment]
Should be easy from the app store (alternatively, you can reinstall xcode). Let me know if you need help

**Comment by FabioLuporini** [comment]
Hi @dekape , did you fix this eventually, and if yes, how?

**Comment by FabioLuporini** [comment]
I assume this was fixed, feel free to reopen otherwise
