### ISSUE TITLE
Installation error while using anaconda

### ISSUE THREAD

**Issue by tgautam03** [opesci/devito#776]
I've followed the instructions precisely as mentioned. I'm using anaconda3. Here's the error that I'm getting. 

![Screenshot from 2019-03-13 17-50-58](https://user-images.githubusercontent.com/30533136/54199718-a2c1e780-44ef-11e9-8929-89c930f171ae.png)

Thanks

**Comment by navjotk** [comment]
Looks like you don't have a C compiler installed.

**Comment by tgautam03** [comment]
I was able to get around this error and have installed everything without any errors but as I run the tutorial file, it gives the following error.
![Screenshot from 2019-03-12 17-46-35](https://user-images.githubusercontent.com/30533136/54211930-1ec82980-4508-11e9-8597-0c61ae7f1408.png)
