### ISSUE TITLE
no module named 'examples'

### ISSUE THREAD

**Issue by tgautam03** [opesci/devito#778]
I've installed devito using conda. I'm trying to run the jupyter notebook in the tutorial section and it's not executing and giving the error 
![nomodule](https://user-images.githubusercontent.com/30533136/54221899-5b048580-451a-11e9-89eb-f6eb1a43d6f9.png)

**Comment by mloubout** [comment]
Did you install jupyter from within your conda environment. Jupyter has the bad habit of skipping environment if already installed

**Comment by tgautam03** [comment]
jupyter was already installed when I installed anaconda. I didn't install it separately. You are suggesting that I install it again within the environment or do something else so that it recognizes the environment packages?

**Comment by btrb** [comment]
@tgautam03 what happens when you go into your terminal and after doing `source activate devito` type `ipython` and then `from devito import *` ?

**Comment by tgautam03** [comment]
I've used nb_conda and was able to resolve this error.
