### ISSUE TITLE
Print statement

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#79]
Hi
Please put parenthesis to all the print statements: 

`print("stuff to print")`
not 
`print "stuff to print"`

The second one makes everything crash with python 3.x

I replaced all of it in my current PR  but please remember it for the future.

**Comment by vincepandolfo** [comment]
Do we need Python 3?

**Comment by mloubout** [comment]
We're not the only one using this, and some (will) use python 3

**Comment by vincepandolfo** [comment]
Anyway, a good point to make is that we shouldn't use `print` statements but Devito `logger` class

**Comment by FabioLuporini** [comment]
We should *never* use ``print``. We should rather use the ``logger`` module. You can use parentheses in there if you think are needed.
