### ISSUE TITLE
Line length must be below 90

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#83]
I'm happy with a straw poll, and maybe we don't really want to set a strict rule, but we should really stop writing long lines of code

PEP8 says 80, I think 90 is OK.

If necessary we should add the rule. 

Opinions ? 

If we decide to add the rule (such that flake8 complains if broken), please @vincepandolfo  add it ASAP (im not sure I'll be looking into this as of tomorrow)

**Comment by vincepandolfo** [comment]
If we want to reduce the limit on line length, then complying with PEP8 (79 char max) is the best choice.

I do agree with reducing the limit to 79

**Comment by mlange05** [comment]
Addressed in PR #95.
