### ISSUE TITLE
How to set up MPI communicator

### ISSUE THREAD

**Issue by wyzhang120** [opesci/devito#835]
The Grid class has an optional parameter "comm", but I couldn't find any documentation on how to define the MPI communicator in devito. Any help on this would be appreciated.

"class devito.grid.Grid(shape, extent=None, origin=None, dimensions=None, time_dimension=None, dtype=<class 'numpy.float32'>, comm=None)"

The "04 - Full waveform inversion with Devito and Dask"  is the only example that I could find which utilized parallel computing. I am not sure if dask.distributed.Client is the same as "comm". If these two are different, please advise which one is preferred.

**Comment by btrb** [comment]
If you're up to date with Devito`s `master`, checkout the branch `mpi-notebook`, then take a look on the notebook (yet under development) at `examples/userapi/mpi.ipynb`. I hope that might be clarifying.

**Comment by FabioLuporini** [comment]
I think this has been discussed on Slack. I'm closing the issue, but feel free to reopen if you need to
