### ISSUE TITLE
Different results with different number of MPI ranks (dependent on source injection, stencil, and dse)

### ISSUE THREAD

**Issue by jrt54** [opesci/devito#836]
I did my best to find a simpler stencil to replicate this issue, but couldn't find anything simpler than my TTI-like stencil. 

The norm of my result is different based on the number of ranks I use. If I output the data itself, I'll see a small but significant difference that is larger near the location of the source injection.

```
#!/bin/bash 

bash set_omp_pinning.sh hsw

exe='unit_test.py'

python $exe
#Norm of u is : 258.071029 

np=4 #fails test with 4 ranks

mpiexec -n $np python $exe 
#Norm of u is : 252.530660
```

Attached is the python script I'm using:
[unit_test.py.txt](https://github.com/opesci/devito/files/3228225/unit_test.py.txt)

The following changes cause the difference between the results to go to 0 (or at least within machine precision).

1.) Using 3 ranks instead of 4. 
2.) Changing the location of my source injection to be at a corner instead of the middle of my domain.    `src_location=np.array(model.domain_size)*.0 #this causes no issues with mpi `
3.) Removing the line `configuration['dse']='aggressive' ##turning this off there's almost 0 difference`
4.) Changing the stencils to be e.g. isotropic acoustic instead of coming from TTI.

**Comment by FabioLuporini** [comment]
THanks a lot.
I'm assigning this to myself and/or @rhodrin (@ggorman ) We'll try to have a look next week

**Comment by FabioLuporini** [comment]
Thanks to @georgebisbas I have a hypothesis of what could go wrong here. I'll investigate in the coming week

**Comment by FabioLuporini** [comment]
I assume ``v``'s norm is broken too?

**Comment by FabioLuporini** [comment]
update: I think it's an MPI bug. With mpi=1 instead of full (ie no mpi optimizations) it seems to be working (at least the 4 cores case)

**Comment by FabioLuporini** [comment]
update: Issue seems to be that we're performing fewer halo exchanges than needed.

**Comment by jrt54** [comment]
I can confirm v's norm is broken as well. 

I tried running with mpi configuration set to 1. Bug still exists on my end. The norms are closer, but still different. And the actual output values are different around the source injection. 

This is with the intel compiler.

**Comment by FabioLuporini** [comment]
Might it be just tolerance. In parallel, they wont be bitwise identical. How different are they?

**Comment by FabioLuporini** [comment]
Update: I have added an MFE to the `fix-mpi-halos` branch

**Comment by FabioLuporini** [comment]
> Might it be just tolerance. In parallel, they wont be bitwise identical. How different are they?

reminder @jrt54

**Comment by jrt54** [comment]
Thanks for the patience, I found other unexplained bugs while trying to test the mpi configuration and thought it might be in my script. I was getting different results even when running two seperate serial jobs (one rank) and using one thread (by setting OMP_NUM_THREADS to 1 in my environment variables). This might have been an unrelated issue that would explain why I was still seeing issues with mpi=full. 

Back to this specific ticket, where I set OMP_NUM_THREADS to 2 in each run. I only got the difference in results when the configuration was set to 'full', as you said. 

What's an MFE? I'm still getting the same behavior on the fix-mpi-halos branch.

**Comment by georgebisbas** [comment]
> What's an MFE? 
Minimal failing example

**Comment by FabioLuporini** [comment]
Hi @jrt54 , no there's still a bug and I'm looking into a proper fix, but my TODO list is actually growing these days . Will keep you posted

**Comment by FabioLuporini** [comment]
and yes, it was two bugs . One fixed; there other still in progress

**Comment by FabioLuporini** [comment]
Update: made significant progress in the ``fix-mpi-halos-3`` branch. Still one last thing to fix

**Comment by FabioLuporini** [comment]
this should now be fixed in ``fix-mpi-halos-3``. Could you try it out?

It seems to be producing the correct norms with all possible MPI schemes (basic, overlap, full, ...) and with ``dse=aggressive`` too.

Haven't tested mixed OpenMP+MPI (can you, or I will later on this week. In fact, I just pushed the branch, so some tests will actually be attempted by CI)

**Comment by FabioLuporini** [comment]
@jrt54 this is now in PR #868 , which hopefully will be merged soon

I'll close this issue as soon as it lands, but please feel free to reopen if there still are inconsistencies

**Comment by FabioLuporini** [comment]
#868 has landed, so I'm closing this. Let me know as soon as you have some spare time :)

**Comment by jrt54** [comment]
I can confirm it worked without OpenMP. Will confirm OpenMP + MPI when I get a chance to test

**Comment by jrt54** [comment]
The job worked for me with openmp=True and mpi=1. Results returned now appear to be the same. But with mpi full and openmp I got this: "TypeError: zip argument #1 must support iteration". Also got a warning "DSE: Couldn't optimize some of the detected redundancies"

**Comment by FabioLuporini** [comment]
> "DSE: Couldn't optimize some of the detected redundancies"
this is expected

> But with mpi full and openmp I got this: "TypeError: zip argument #1 must support iteration"
This is _kinda_ expected , but first of all I really wanted to make MPI full functional again. You're the first one trying it in combination with OpenMP -- no specific reasons why it shouldn't have just worked, 
but there are just a few simple tests for OpenMP+MPI, so I'm not too surprised some minor fixing is expected. Will do later on
