### ISSUE TITLE
Temporaries issue in some cases

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#851]
So there is a very "hidden/nasty" bug with dse/dle (not sure yet exactly but I think it's dse) that some of the temporaries `rxx` are either not declared or in some case moved to the Kernel signature as an input.

One failure is 

`python examples/seismic/tti/tti_example.py -dse aggressive --2d` 

that fails to compile due to undeclared temporary
```
/var/folders/mx/qs0dn9rx7zn6dz2zvwv7tkk00000gn/T/devito-jitcache-uid501/b665ace9fedca5fcbd0d0756a9adb7ee498d1f03.c: In function 'ForwardTTI':
/var/folders/mx/qs0dn9rx7zn6dz2zvwv7tkk00000gn/T/devito-jitcache-uid501/b665ace9fedca5fcbd0d0756a9adb7ee498d1f03.c:83:53: error: 'r43' undeclared (first use in this function); did you mean 'r45'?
           float r45 = 5.00000007e-2F*(r27[x + 1][y]*r43[x + 1][y] - r27[x + 1][y + 2]*r43[x + 1][y + 2] + r28[x][y + 1]*r43[x][y + 1] - r28[x + 2][y + 1]*r43[x + 2][y + 1]);
                                        
```

**Comment by FabioLuporini** [comment]
this is now fixed in master (after #842 and #868 landed), so closing
