### ISSUE TITLE
Getting velcoity model with pml as np array

### ISSUE THREAD

**Issue by HNossrati** [opesci/devito#866]
Hi
Is there any way to get the velocity model with pml boundaries output as an np array in seismic examples?

**Comment by mloubout** [comment]
you can access any parameter in the model as `model.m` (squared slowness) and `model.m.data` to get the array. `vp` is also stored into `model._vp` as a raw numpy array
Feel free to join our slack channel where we will be quicker to respond.
https://opesci-slackin.now.sh/

**Comment by HNossrati** [comment]
> you can access any parameter in the model as `model.m` (squared slowness) and `model.m.data` to get the array. `vp` is also stored into `model._vp` as a raw numpy array
> Feel free to join our slack channel where we will be quicker to respond.
> https://opesci-slackin.now.sh/

Thank you for your response
I  had tried model._vp but it doesn't have the pml around it. Also, I tried 'model.damp.data' but it doesn't seem true. I want to know is there any way to get the velocity model with the PML

**Comment by mloubout** [comment]
The velocity is smever extended and damped as you only need m or vp and both is a waste of memory.

model.damp is the dampening mask not the velocity

But it is trivial to get the velocity from model.m it's just sqrt(1/m)

**Comment by HNossrati** [comment]
Ok, thanks
