### ISSUE TITLE
How to install Devito on Windows 10

### ISSUE THREAD

**Issue by AlbertZhangHIT** [opesci/devito#867]
Hi, 
I failed to install devito on Windows 10, is it only available for Linux?

**Comment by mloubout** [comment]
Please look at our installation page
https://github.com/opesci/devito/wiki/Installation-Issues

We strongly recommend docker or VM for windows. You can also join our slack channel https://opesci-slackin.now.sh/ where we have a dedicated installation discussion and more people may help.

**Comment by FabioLuporini** [comment]
Closing this since I haven't seen updates in the last 4 days. Feel free to reopen, with a suitable error trace, if still failing
