### ISSUE TITLE
OPS test is incorrect

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#893]
https://github.com/opesci/devito/blob/935621d5f020b08f3a229a53632b304a9761c8e0/tests/test_ops.py#L34

This test produces a wrong stencil but test it against it so passes, `.dxl` and `.dxr` have indices `x, x+hx, x+2hx` (or minus sign) the test produces stencil that only has `x, x+2hx`. (index 0, +2 and -2)

This test needs to be fixed asap as this makes me think like the ops backend is processing the stencils incorrectly.

@vincepandolfo and OPS team please look at it as `expected` should contain all of `vt0(0, 1), vt0(0, -1), vt0(1, 0), vt0(-1, 0)`

**Comment by FabioLuporini** [comment]
Im removing myself from this and reassigning to @btrb which subsumes his team , and @vincepandolfo

**Comment by btrb** [comment]
ok, we will have a look now

in fact, just run the test and it returned a Fail in:

```
>       assert result[1].expr.rhs.name == namespace['ops_decl_stencil'].name
E       AttributeError: 'ops_decl_stencil' object has no attribute 'name'

tests/test_ops.py:120: AttributeError
```
which is weird regarded that @vincepandolfo cleverly defined `namespace['ops_decl_stencil']` as a `Function`

**Comment by btrb** [comment]
it seems the correct `space_indices` are being generated in `new_ops_arg` at `OPSNodeFactory` for the case 

`Eq(v,v.dxl + v.dxr - v.dyr - v.dyl)`

```
[0, 0]
[-2, 0]
[0, 2]
[2, 0]
[0, -2]
[1, 0]
[0, -1]
[-1, 0]
[0, 1]
```

so it seems the method is not completely broken

**Comment by btrb** [comment]
the last `expr.expr` from [here](https://github.com/opesci/devito/blob/master/devito/ops/transformer.py#L34) seems to be ok:

`Eq(v[t0, x, y], 0.5*(r0*v[t0, x - 2, y] - r0*v[t0, x + 2, y] - r1*v[t0, x, y - 2] + r1*v[t0, x, y + 2]) + 2.0*(-r0*v[t0, x - 1, y] + r0*v[t0, x + 1, y] + r1*v[t0, x, y - 1] - r1*v[t0, x, y + 1]))`

to the problem must be either in `make_ops_ast` or in `node_factory`

**Comment by btrb** [comment]
i'm not quite sure yet, but it seems the problem might be at the case `else` in the recurson at `make_ops_ast` [[lind](https://github.com/opesci/devito/blob/master/devito/ops/transformer.py#L117)].

i think it's building `devito.symbolics.extended.sympy.Add` with the same `nfops.ops_args_accesses` for both `args` (lhs and rhs) in the list of `expr.args`

**Comment by vincepandolfo** [comment]
```

**Comment by vincepandolfo** [comment]
before
-r1*v[t0][x][y + 1]
after
-1
vt0(0, 1)
r1
-vt0(0, -2)*r1
```
Some crude debug output from `make_ops_ast`.
`before` is the `expr` as it goes in the `else` clause, `after` is the args array and the resulting expr. It seems the arguments are calculated correctly, but when `expr.func` is called the indexes go out of whack

**Comment by vincepandolfo** [comment]
Found the problem. `hashable_content` in `OpsAccess` only returns `self.base`, therefore it's only caching one access
