### ISSUE TITLE
Numpy dependency

### ISSUE THREAD

**Issue by navjotk** [opesci/devito#96]
In trying to install devito on the yemoja cluster I realised the following:
- Our `requirements.txt` does not list numpy as a dependency
- Travis.yaml does not download/install numpy in any special way
- The tests pass on travis
- Running the same tests on the cluster, with numpy `1.8`, 3 tests fail. These same tests pass on version `1.11` of numpy.

Which version of numpy do we need?
Should this be added to requirements.txt? 
How does travis know which version of numpy to use?

**Comment by mlange05** [comment]
Is this fixed now by PR #129?

**Comment by mlange05** [comment]
@navjotk Is this now fixed by PR #129?

**Comment by navjotk** [comment]
Yes it is, thanks. Closing.
