### ISSUE TITLE
rename nbpml as nbl in /examples

### ISSUE THREAD

**Issue by FabioLuporini** [opesci/devito#972]
`nbpml` is a misleading name -- our examples do **not** use PMLs

``nbl`` is a much more generic name

**Comment by btrb** [comment]
so what would be the appropriate named instead [?](https://github.com/opesci/devito/pull/973/files/f3fb5dd4fcd1b331757ba0d876970209abbb7ef9#r337473974)

**Comment by FabioLuporini** [comment]
nb=number 
l=layer

**Comment by FabioLuporini** [comment]
fixed by #986
