### ISSUE TITLE
The Devito `gaussian_smooth` builtin does not replicate `scipy.ndimage.gaussian_filter` behaviour

### ISSUE THREAD

**Issue by rhodrin** [opesci/devito#977]
Currently, the devito `gaussian_smooth` builtin:

1. Lacks all the features of its scipy counterpart. Some features are being added in the `devito_smooth` branch but which features do we wish to prioritize?
2. Does not work correctly when the input data is an array of floats. (This is fixed in the `devito_smooth` branch).
3. For arrays of type `int`, it 'can' return slightly different results compared to the scipy version depending on the input data and sigma.

With regards to 3, this appears to stem from differences in how types are stored and when they are converted. I think we need to come to a consensus regarding what behavior we want.

**Comment by FabioLuporini** [comment]
@mloubout

**Comment by mloubout** [comment]
So basically:
1- fixed
2- fixed
3- Non-issue. We have a smoother that works correctly and is tested, slight numerical accuracy and type conversion differences are non-issue

closing.
