### ISSUE TITLE
Pre/Post stencils loops generation

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#98]
@mlange05 
I' don't know if I missed something but this lines trouble me : 
```
        # Statements to be inserted into the time loop before the spatial loop
        time_loop_stencils_b = [self.time_substitutions(x)
                                for x in self.time_loop_stencils_b]
        time_loop_stencils_b = [self.convert_equality_to_cgen(x)
                                for x in self.time_loop_stencils_b]

        # Statements to be inserted into the time loop after the spatial loop
        time_loop_stencils_a = [self.time_substitutions(x)
                                for x in self.time_loop_stencils_a]
        time_loop_stencils_a = [self.convert_equality_to_cgen(x)
                                for x in self.time_loop_stencils_a]
```

The first statement is overwritten by the second one isn't it? If yes is it on purpose and can the `time_substittion` line be removed or is the second one supposed to act on `time_loop_stencils_a` instead of `self.time_loop_stencils_a`

**Comment by FabioLuporini** [comment]
Yes, this is odd. I think you can safely delete the first line in each block.

**Comment by mlange05** [comment]
Ok, turns out you can't, as demonstrated by the segfaulting in the `remove-time-subs-stencil-loops` branch. The reason, I believe, is that `time_substitutions` performs the substitutions in-place for the `Iteration` objects, which means the resulting code is actually updated although we ignore the return value.

**Comment by mloubout** [comment]
OK thanks for the details. Can be closed then
