### ISSUE TITLE
Load/store OI calculations potentially should be done without Profiling.

### ISSUE THREAD

**Issue by sheino** [opesci/devito#99]
Info like `OI` or `load count` might be needed even if we are running with `profiling=False`.

For example when estimating optimal block size `load count` is always needed.
 As a workaround I had to create an additional temporally `profiler` which would extract it even when `profiling = False`.

For future use , we might need to move the load/store and OI calculations back to the sympy expressions

**Comment by vincepandolfo** [comment]
We might add a static method in `Profiler` that takes a Sympy expression and returns this info.
