### ISSUE TITLE
'Data' object has no attribute 'inject' (Adjoint Implementation)

### ISSUE THREAD

**Issue by hongweioliver** [opesci/devito#996]
First of all, this is an awesome tool for geophysical application. Thanks for developing it.  Currently, I am trying to implement the adjoint method in Devito.  When I was trying to inject the L2 norm into the adjoint function, it shows me that  'Data' object has no attribute 'inject'. Anyone knows how to solve this problem?  

If there is some tutorials on implementing adjoint inversion from scratch using current devito, it would help me a lot.  

Thanks for the help.

**Comment by rhodrin** [comment]
Hi @hongweioliver,

Glad you're finding devito useful and thanks for the comments!

It would help if you could share your code so we can take a closer look at what's going wrong.

Also, did you take a look at the FWI tutorial?
https://github.com/opesci/devito/blob/master/examples/seismic/tutorials/03_fwi.ipynb

**Comment by hongweioliver** [comment]
Hi @rhodrin 

I think Devito is the best tool I can find right now. Thank you very much for the quick response. 

I did follow the FWI tutorial. But I am wondering how it is implemented because I want to implement elastic adjoint inversion and other stuff later on.  Other than the FWI tutorial (2017 ,2018 and current version) , I also read a few papers on that but it did not work. 

1. High-level python abstractions for optimal checkpointing in inversion problems
2. Devito (v3.1.0): an embedded domain-specific language for finite differences and geophysical exploration

Please find the attached code.  Thanks again for your help. 

Hongwei 


![5problem](https://user-images.githubusercontent.com/40039421/68320534-bf65ed80-0085-11ea-8b07-736e01762d75.PNG)
![1adjoint](https://user-images.githubusercontent.com/40039421/68320535-bf65ed80-0085-11ea-99b1-c62e891f104b.PNG)
![2data](https://user-images.githubusercontent.com/40039421/68320536-bf65ed80-0085-11ea-9bb8-f1eb8b38dc85.PNG)
![3u](https://user-images.githubusercontent.com/40039421/68320537-bf65ed80-0085-11ea-9217-6762d4151e2c.PNG)
![4residual](https://user-images.githubusercontent.com/40039421/68320538-bf65ed80-0085-11ea-94de-57a5ebd73b86.PNG)

**Comment by mloubout** [comment]
Hi, thanks for the attention.

Your main issue lie in cell `22` where you do
`residual = data1.data - data2.data`.

By doing so, `residual` is not a Receiver anymore but a simple Data object, mainly a numpy array, while the operator expects a `Receiver`. There is two way to fix that easily following what I did the fyi notebook @rhodrin pointed you too, mainly assign the residual to the data of `residual.

1- assign the residual to the data : `residual.data[:] = data1.data[:] - data2.data[:]`
In that case `residual` stays a `Receiver` and `adjoint` should run smoothly

2- If you want a more robust (w.r.t MPI for example) way. You can create a "residual operator:
`Operator(Eq(residual, data1 - data2)`. That second one may need some tweaking of dimension to work properly so I would concentrate on the first option.

**Comment by hongweioliver** [comment]
Hi @mloubout 

Thanks a lot. It works now.  Thanks again for creating that FWI tutorial. 

Have a nice day

Hongwei

**Comment by mloubout** [comment]
Glad to hear, closing the issue.
